classdef buildMixedLoopShapingSamplesTest < matlab.unittest.TestCase
    %BUILDMIXEDLOOPSHAPINGSAMPLESTEST Dynamic transformation tests.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'src')));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testZeroFrequencyMatchesPowerPolarTransformation(testCase)
            operatingPoint = testCase.operatingPoint();
            static = buildPowerPolarLinearization(operatingPoint);
            converter = [1+0.2i, 0.3; -0.1i, 0.8];
            network = [2-0.1i, -0.4; 0.2i, 1.5];

            result = buildMixedLoopShapingSamples( ...
                {converter}, network, 0, {operatingPoint}, {eye(2)}, ...
                testCase.options());

            testCase.verifyEqual(result.C{1}(:, :, 1), static.C, ...
                AbsTol=1e-14);
            testCase.verifyEqual(result.F{1}(:, :, 1), static.F, ...
                AbsTol=1e-14);
            testCase.verifyEqual(result.converterResponses{1}(:, :, 1), ...
                (static.E*converter+static.C)*static.F, AbsTol=1e-13);
            testCase.verifyEqual(result.networkResponse(:, :, 1), ...
                (static.E*network-static.C)*static.F, AbsTol=1e-13);
        end

        function testSampleMatchesDirectDynamicFormula(testCase)
            operatingPoint = testCase.operatingPoint();
            static = buildPowerPolarLinearization(operatingPoint);
            converter = [1+0.2i, 0.3; -0.1i, 0.8];
            frequencyHz = 1;
            cutoffHz = 0.5;
            lowPass = cutoffHz/(1i*frequencyHz+cutoffHz);
            highPass = 1-lowPass;
            weighting = [0.7+0.1i, -0.2; 0.2, 0.7+0.1i];
            expectedC = lowPass*static.C;
            expectedF = lowPass*static.F + ...
                highPass*(weighting/static.E);
            expected = (static.E*converter+expectedC)*expectedF;

            result = buildMixedLoopShapingSamples({converter}, eye(2), ...
                frequencyHz, {operatingPoint}, {weighting}, ...
                testCase.options(struct('CutoffHz', cutoffHz)));

            testCase.verifyEqual(result.converterResponses{1}, expected, ...
                AbsTol=1e-13);
            highFrequencyComponent = ...
                (result.F{1}-lowPass*static.F)/highPass;
            testCase.verifyEqual(highFrequencyComponent*static.E, ...
                weighting, AbsTol=1e-13);
            testCase.verifyGreaterThan( ...
                norm(highFrequencyComponent-static.E\weighting, 'fro'), ...
                1e-3);
        end

        function testTwoConverterInterconnectionIdentity(testCase)
            frequenciesHz = [0, 1, 50];
            converter1 = repmat(eye(2), 1, 1, 3);
            converter2 = repmat(2*eye(2), 1, 1, 3);
            networkSample = [ ...
                3*eye(2), [0.2, -0.1; 0.05, 0.3]; ...
                [-0.15, 0.04; 0.07, -0.2], 2.5*eye(2)];
            network = repmat(networkSample, 1, 1, 3);
            weight1 = repmat(eye(2), 1, 1, 3);
            weight2 = repmat([1, -0.1; 0.1, 1], 1, 1, 3);
            operatingPoint1 = testCase.operatingPoint();
            operatingPoint2 = struct( ...
                'vd', 1.1, 'vq', -0.2, 'id', -0.3, 'iq', 0.1);

            result = buildMixedLoopShapingSamples( ...
                {converter1, converter2}, network, frequenciesHz, ...
                {operatingPoint1, operatingPoint2}, {weight1, weight2}, ...
                testCase.options());

            testCase.verifyLessThan( ...
                max(result.interconnectionResidual), 1e-13);
            testCase.verifyEqual(result.transformationStatus, ...
                repmat("sampled-algebra-resolved", 1, 3));
            testCase.verifyEqual(result.dynamicPreconditionsStatus, ...
                "not-evaluated");
            testCase.verifyEqual(result.assessmentScope, ...
                "sampled-frequency-algebra");
            for index = 1:numel(frequenciesHz)
                expected12 = result.E{1}*networkSample(1:2, 3:4)* ...
                    result.F{2}(:, :, index);
                expected21 = result.E{2}*networkSample(3:4, 1:2)* ...
                    result.F{1}(:, :, index);
                testCase.verifyEqual( ...
                    result.networkResponse(1:2, 3:4, index), ...
                    expected12, AbsTol=1e-13);
                testCase.verifyEqual( ...
                    result.networkResponse(3:4, 1:2, index), ...
                    expected21, AbsTol=1e-13);
            end
        end

        function testHighFrequencyApproachesWeightedSimilarity(testCase)
            operatingPoint = testCase.operatingPoint();
            static = buildPowerPolarLinearization(operatingPoint);
            weighting = [1, -0.1; 0.1, 1];

            result = buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(2), 1e10, {operatingPoint}, ...
                {weighting}, testCase.options());

            testCase.verifyEqual(result.C{1}(:, :, 1), zeros(2), ...
                AbsTol=1e-10);
            testCase.verifyEqual(result.F{1}(:, :, 1), ...
                weighting/static.E, AbsTol=1e-10);
        end

        function testIllConditionedHighFrequencyFIsPending(testCase)
            operatingPoint = testCase.operatingPoint();
            rankOneWeighting = [1, 0; 0, 0];
            options = testCase.options(struct( ...
                'MaxTransformationConditionNumber', 10));

            result = buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(2), 1e12, {operatingPoint}, ...
                {rankOneWeighting}, options);

            testCase.verifyEqual( ...
                result.transformationStatus, "numerical-pending");
            testCase.verifyTrue(any(result.reasonCodes{1} == ...
                "ill-conditioned-F"));
        end

        function testMismatchedNetworkDimensionIsRejected(testCase)
            operatingPoint = testCase.operatingPoint();

            testCase.verifyError(@() buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(4), 1, {operatingPoint}, {eye(2)}, ...
                testCase.options()), ...
                'gfm:buildMixedLoopShapingSamples:InvalidResponse');
        end

        function testConventionMetadataIsRequired(testCase)
            operatingPoint = testCase.operatingPoint();

            testCase.verifyError(@() buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(2), 1, {operatingPoint}, {eye(2)}, struct()), ...
                'gfm:buildMixedLoopShapingSamples:InvalidConvention');
        end

        function testAuthorConventionRequiresLoadDirection(testCase)
            operatingPoint = testCase.operatingPoint();
            options = testCase.options();
            options.ConventionMetadata.frameConventionId = ...
                "cifelli-anta-author-global-synchronous-dq-v1";

            testCase.verifyError(@() buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(2), 1, {operatingPoint}, {eye(2)}, options), ...
                'gfm:buildMixedLoopShapingSamples:InvalidConvention');

            options.ConventionMetadata.converterCurrentDirection = ...
                "network-to-converter";
            options.ConventionMetadata.networkCurrentDirection = ...
                "converter-to-network";
            options.ConventionMetadata.powerConvention = "load-positive";
            result = buildMixedLoopShapingSamples( ...
                {eye(2)}, eye(2), 1, {operatingPoint}, {eye(2)}, options);
            testCase.verifyEqual(result.transformationStatus, ...
                "sampled-algebra-resolved");
        end
    end

    methods (Static, Access=private)
        function value = operatingPoint()
            value = struct('vd', 0.8, 'vq', 0.3, ...
                'id', 0.4, 'iq', -0.2);
        end

        function value = options(overrides)
            if nargin < 1
                overrides = struct();
            end
            value = overrides;
            value.ConventionMetadata = struct( ...
                'frameConventionId', ...
                    "analytic-test-global-synchronous-dq-v1", ...
                'converterCurrentDirection', "converter-to-network", ...
                'networkCurrentDirection', "network-to-converter", ...
                'powerConvention', "injection-positive");
        end
    end
end
