classdef refineMixedGainPhaseFrequencyGridTest < matlab.unittest.TestCase
    %REFINEMIXEDGAINPHASEFREQUENCYGRIDTEST Adaptive model-level screening.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'src')));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testSamplingAloneNeverClaimsBranchProof(testCase)
            options = testCase.options();
            options.MaxIterations = 2;

            result = refineMixedGainPhaseFrequencyGrid( ...
                @testCase.wholeTurnModel, [0, 1], ...
                testCase.conventions(), testCase.preconditions(), options);

            testCase.verifyGreaterThan(result.frequencyPointCount, 2);
            testCase.verifyEqual(result.frequenciesHz([1, end]), [0, 1]);
            testCase.verifyTrue(all(diff(result.frequenciesHz) > 0));
            testCase.verifyEqual(result.refinementStatus, ...
                "refined-screening-only");
            testCase.verifyEqual(result.theoremStatus, ...
                "not-evaluated-by-adaptive-sampling-api");
            testCase.verifyEqual(result.stopReason, ...
                "maximum-iterations-reached");
            testCase.verifyEqual(result.history(1).sampledBandStatus, ...
                "covered-on-grid-under-phase-branch-assumption");
            testCase.verifyEqual(result.evaluation.sampledBandStatus, ...
                "not-covered-on-grid-under-phase-branch-assumption");
            testCase.verifyTrue(all( ...
                [result.history.phaseBranchVerificationStatus] == ...
                "indeterminate"));
            a = 2*pi/sqrt(3);
            closedLoopPoles = roots([1, -9*a, 3*a^2, -3*a^3]);
            testCase.verifyGreaterThan(max(real(closedLoopPoles)), 0);
        end

        function testCertifiedVariationBoundStopsImmediately(testCase)
            options = testCase.options();
            options.MaxIterations = 3;
            options.VariationBoundEvaluator = ...
                @testCase.suppliedSmallBounds;

            result = refineMixedGainPhaseFrequencyGrid( ...
                @testCase.slowPhaseModel, [0, 1], ...
                testCase.conventions(), testCase.preconditions(), options);

            testCase.verifyEqual(result.refinementStatus, ...
                "phase-branches-verified-under-supplied-bounds");
            testCase.verifyEqual(result.stopReason, ...
                "all-phase-branches-verified-under-supplied-bounds");
            testCase.verifyEqual(result.frequencyPointCount, 2);
        end

        function testInvalidBoundsRemainScreeningOnly(testCase)
            options = testCase.options();
            options.MaxIterations = 1;
            options.VariationBoundEvaluator = ...
                @testCase.inadequateBounds;

            result = refineMixedGainPhaseFrequencyGrid( ...
                @testCase.slowPhaseModel, [0, 1], ...
                testCase.conventions(), testCase.preconditions(), options);

            testCase.verifyEqual(result.refinementStatus, ...
                "refined-screening-only");
            testCase.verifyTrue(any( ...
                result.phaseBranchVerification.intervalStatus(:) ~= ...
                "verified"));
        end

        function testSingularNetworkRemainsIndeterminate(testCase)
            options = testCase.options();
            options.MaxIterations = 0;

            result = refineMixedGainPhaseFrequencyGrid( ...
                @testCase.singularNetworkModel, [0, 1], ...
                testCase.conventions(), testCase.preconditions(), options);

            testCase.verifyEqual(result.refinementStatus, ...
                "refined-screening-only");
            testCase.verifyEqual( ...
                result.phaseBranchVerification.verificationStatus, ...
                "indeterminate");
        end
    end

    methods (Static, Access=private)
        function samples = wholeTurnModel(frequenciesHz)
            omega = 2*pi*frequenciesHz;
            a = 2*pi/sqrt(3);
            allPass = ((a-1i*omega)./(a+1i*omega)).^3;
            samples = struct( ...
                'converterResponses', ...
                    {{reshape(2*allPass, 1, 1, [])}}, ...
                'networkResponse', ones(1, 1, numel(frequenciesHz)), ...
                'modelHash', "whole-turn-model-v1");
        end

        function samples = slowPhaseModel(frequenciesHz)
            phase = 0.2*frequenciesHz;
            samples = struct( ...
                'converterResponses', ...
                    {{reshape(2*exp(1i*phase), 1, 1, [])}}, ...
                'networkResponse', ones(1, 1, numel(frequenciesHz)), ...
                'modelHash', "slow-phase-model-v1");
        end

        function samples = singularNetworkModel(frequenciesHz)
            samples = struct( ...
                'converterResponses', ...
                    {{ones(1, 1, numel(frequenciesHz))}}, ...
                'networkResponse', zeros(1, 1, numel(frequenciesHz)), ...
                'modelHash', "singular-network-model-v1");
        end

        function result = suppliedSmallBounds(frequenciesHz, modelSamples)
            count = numel(frequenciesHz)-1;
            increments = 0.2*diff(frequenciesHz);
            result = struct( ...
                'responseDeviationUpperBound2Norm', ...
                    [2*increments; zeros(1, count)], ...
                'rotationThetaRad', ...
                    [0.2*(frequenciesHz(1:end-1)+ ...
                        frequenciesHz(2:end))/2; zeros(1, count)], ...
                'frequencyGridHz', frequenciesHz, ...
                'responseIds', ["converter:1"; "network-inverse"], ...
                'frequencyUnit', "Hz", ...
                'boundMethod', "analytic-chord-upper-bound", ...
                'modelHash', string(modelSamples.modelHash), ...
                'referencePoint', "left-endpoint", ...
                'assuranceLevel', "double-precision-numerical-bound", ...
                'floatingPointCertified', false, ...
                'roundoffBoundIncluded', false, ...
                'independentVariable', "frequency", ...
                'derivativeUnit', "per-Hz");
        end

        function result = inadequateBounds(frequenciesHz, modelSamples)
            result = refineMixedGainPhaseFrequencyGridTest. ...
                suppliedSmallBounds(frequenciesHz, modelSamples);
            result.responseDeviationUpperBound2Norm(:) = 3;
        end

        function options = options()
            options = struct('EvaluationOptions', struct( ...
                'PhaseCenterSeeds', struct( ...
                    'converterCenters', 0, ...
                    'networkInverseCenter', 0)));
        end

        function conventions = conventions()
            conventions = struct( ...
                'frameConventionId', ...
                    "analytic-test-global-synchronous-dq-v1", ...
                'currentDirection', "converter-to-network", ...
                'powerDirection', "injection-positive", ...
                'sBase', 1, ...
                'vBase', 1, ...
                'fBase', 50, ...
                'matrixType', "admittance", ...
                'globalFrameId', "adaptive-test-global-dq");
        end

        function preconditions = preconditions()
            preconditions = struct( ...
                'openLoopStable', true, ...
                'realRationalProper', true, ...
                'transformationWellDefined', true, ...
                'networkInverseStable', true, ...
                'noRhpCancellation', true, ...
                'endpointsCovered', false, ...
                'fullFrequencyCoverage', false);
        end
    end
end
