classdef runAuthorFig8MixedRegressionTest < matlab.unittest.TestCase
    %RUNAUTHORFIG8MIXEDREGRESSIONTEST Controlled author-case regression.

    methods (TestClassSetup)
        function addExperimentFolder(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'experiments', 'baseline')));
        end
    end

    methods (Test, TestTags = {'Integration', 'Slow'})
        function testControlledDampingCasesMatchPinnedScreening(testCase)
            result = run_author_fig8_mixed_regression();
            unstable = result.cases(1);
            stable = result.cases(2);

            testCase.verifyEqual(unstable.caseId, "fig8_D_0p05");
            testCase.verifyFalse(unstable.closedLoopStableOnPinnedSpectrum);
            testCase.verifyEqual(unstable.maximumRealPoleHz, ...
                0.021154437116, AbsTol=1e-10);
            testCase.verifyEqual(unstable.converterPhaseSeedIndex, 39);
            testCase.verifyEqual(unstable.screening.sampledBandStatus, ...
                "not-covered-on-grid-under-phase-branch-assumption");
            testCase.verifyEqual(nnz(unstable.screening.gainStatus == ...
                "fail"), 615);
            testCase.verifyEqual(nnz(unstable.screening.phaseStatus == ...
                "fail"), 422);
            testCase.verifyEqual(nnz(unstable.screening.phaseStatus == ...
                "indeterminate"), 38);
            testCase.verifyEqual(nnz(unstable.screening.sampleCoverage == ...
                "uncovered"), 75);

            testCase.verifyEqual(stable.caseId, "fig8_D_0p5");
            testCase.verifyTrue(stable.closedLoopStableOnPinnedSpectrum);
            testCase.verifyEqual(stable.maximumRealPoleHz, ...
                -0.289891361, AbsTol=1e-9);
            testCase.verifyEqual(stable.converterPhaseSeedIndex, 1);
            testCase.verifyEqual(stable.screening.sampledBandStatus, ...
                "covered-on-grid-under-phase-branch-assumption");
            testCase.verifyEqual(nnz(stable.screening.phaseStatus == ...
                "fail"), 0);
            testCase.verifyEqual(nnz(stable.screening.phaseStatus == ...
                "indeterminate"), 0);
            testCase.verifyEqual(nnz(stable.screening.sampleCoverage == ...
                "uncovered"), 0);

            testCase.verifyLessThan( ...
                max([unstable.maximumInterconnectionResidual, ...
                stable.maximumInterconnectionResidual]), 2e-15);
            testCase.verifyEqual( ...
                unstable.screening.theoremStatus, ...
                "not-evaluated-by-sampled-api");
            testCase.verifyEqual( ...
                stable.screening.theoremStatus, ...
                "not-evaluated-by-sampled-api");
            testCase.verifySubstring(result.screeningBoundary, ...
                "not theorem confirmation");
        end
    end
end
