classdef verifyHalfPlanePhaseBranchIntervalsTest < matlab.unittest.TestCase
    %VERIFYHALFPLANEPHASEBRANCHINTERVALSTEST Interval matrix evidence tests.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectRoot = fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(projectRoot, 'src')));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function testCommonHalfPlaneVerifiesCrossing(testCase)
            centers = deg2rad([170, -175, -160]);
            responses = {reshape(exp(1i*centers), 1, 1, [])};
            evidence = testCase.evidence( ...
                deg2rad([177.5, 192.5]), deg2rad([16, 16]));

            result = verifyHalfPlanePhaseBranchIntervals(responses, ...
                [0, 1, 2], "converter:1", "analytic-test-model-v1", ...
                centers, repmat("resolved", 1, 3), deg2rad(170), 1, evidence);

            testCase.verifyEqual(result.center, ...
                deg2rad([170, 185, 200]), AbsTol=1e-12);
            testCase.verifyEqual(result.verificationStatus, ...
                "branch-verified-under-supplied-deviation-bounds");
            testCase.verifyFalse(result.floatingPointCertified);
        end

        function testWholeTurnCannotUseSmallHalfPlaneBound(testCase)
            centers = [0, 0];
            responses = {reshape([1, 1], 1, 1, [])};
            evidence = testCase.evidence(0, 2);

            result = verifyHalfPlanePhaseBranchIntervals(responses, ...
                [0, 1], "converter:1", "analytic-test-model-v1", ...
                centers, ["resolved", "resolved"], 0, 1, evidence);

            testCase.verifyEqual(result.verificationStatus, "indeterminate");
            testCase.verifyEqual(result.reasonCodes(2), ...
                "common-open-half-plane-not-verified");
        end

        function testFalseDeviationBoundIsRejectedByEndpoints(testCase)
            centers = [0, 0.5];
            responses = {reshape(exp(1i*centers), 1, 1, [])};
            evidence = testCase.evidence(0.25, 0.1);

            result = verifyHalfPlanePhaseBranchIntervals(responses, ...
                [0, 1], "converter:1", "analytic-test-model-v1", ...
                centers, ["resolved", "resolved"], 0, 1, evidence);

            testCase.verifyEqual(result.intervalStatus, "invalid-bound");
            testCase.verifyEqual(result.reasonCodes(2), ...
                "deviation-bound-inconsistent-with-endpoints");
        end

        function testEvidenceForDifferentGridIsRejected(testCase)
            evidence = testCase.evidence(0, 0);
            evidence.frequencyGridHz = [0, 2];

            testCase.verifyError(@() verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1], "converter:1", ...
                "analytic-test-model-v1", [0, 0], ...
                ["resolved", "resolved"], 0, 1, evidence), ...
                'gfm:verifyHalfPlanePhaseBranchIntervals:EvidenceGridMismatch');
        end

        function testEvidenceForDifferentModelIsRejected(testCase)
            evidence = testCase.evidence(0, 0);
            evidence.modelHash = "different-model";

            testCase.verifyError(@() verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1], "converter:1", ...
                "analytic-test-model-v1", [0, 0], ...
                ["resolved", "resolved"], 0, 1, evidence), ...
                'gfm:verifyHalfPlanePhaseBranchIntervals:EvidenceModelMismatch');
        end

        function testFloatingPointCertificationClaimIsRejected(testCase)
            evidence = testCase.evidence(0, 0);
            evidence.floatingPointCertified = true;

            testCase.verifyError(@() verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1], "converter:1", ...
                "analytic-test-model-v1", [0, 0], ...
                ["resolved", "resolved"], 0, 1, evidence), ...
                'gfm:verifyHalfPlanePhaseBranchIntervals:InvalidEvidence');
        end

        function testRawCenterInconsistentWithResponseIsRejected(testCase)
            evidence = testCase.evidence(0, 0);

            testCase.verifyError(@() verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1], "converter:1", ...
                "analytic-test-model-v1", [0, 0.3], ...
                ["resolved", "resolved"], 0, 1, evidence), ...
                'gfm:verifyHalfPlanePhaseBranchIntervals:RawCenterMismatch');
        end

        function testGridLengthMismatchIsRejected(testCase)
            evidence = testCase.evidence(0, 0);
            evidence.frequencyGridHz = [0, 1, 2];

            testCase.verifyError(@() verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1, 2], "converter:1", ...
                "analytic-test-model-v1", [0, 0], ...
                ["resolved", "resolved"], 0, 1, evidence), ...
                'gfm:verifyHalfPlanePhaseBranchIntervals:GridSizeMismatch');
        end

        function testInconsistentExplicitSeedIsIndeterminate(testCase)
            evidence = testCase.evidence(0, 0);
            result = verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1], 1, 1, [])}, [0, 1], "converter:1", ...
                "analytic-test-model-v1", [0, 0], ...
                ["resolved", "resolved"], pi, 1, evidence);

            testCase.verifyEqual(result.verificationStatus, "indeterminate");
            testCase.verifyEqual(result.reasonCodes(1), ...
                "explicit-seed-inconsistent-with-phase-center");
        end

        function testFrequenciesBeforeLaterSeedRemainIndeterminate(testCase)
            evidence = testCase.evidence([0, 0], [0, 0]);
            result = verifyHalfPlanePhaseBranchIntervals( ...
                {reshape([1, 1, 1], 1, 1, [])}, [0, 1, 2], ...
                "converter:1", "analytic-test-model-v1", [0, 0, 0], ...
                repmat("resolved", 1, 3), 0, 2, evidence);

            testCase.verifyEqual(result.branchStatus(1), ...
                "phase-branch-indeterminate");
            testCase.verifyEqual(result.reasonCodes(1), ...
                "phase-before-explicit-seed");
            testCase.verifyEqual(result.branchStatus(2), ...
                "verified-from-explicit-seed");
            testCase.verifyEqual(result.verificationStatus, "indeterminate");
        end

        function testRowVectorSeedIndicesSupportMultipleResponses(testCase)
            evidence = struct( ...
                'responseDeviationUpperBound2Norm', [0; 0], ...
                'rotationThetaRad', [0; 0], ...
                'frequencyGridHz', [0, 1], ...
                'responseIds', ["converter:1"; "network-inverse"], ...
                'frequencyUnit', "Hz", ...
                'boundMethod', "analytic-test-bound", ...
                'modelHash', "two-response-model-v1", ...
                'referencePoint', "left-endpoint", ...
                'assuranceLevel', "double-precision-numerical-bound", ...
                'floatingPointCertified', false, ...
                'roundoffBoundIncluded', false, ...
                'independentVariable', "frequency", ...
                'derivativeUnit', "per-Hz");
            responses = {reshape([1, 1], 1, 1, []); ...
                reshape([1, 1], 1, 1, [])};

            result = verifyHalfPlanePhaseBranchIntervals(responses, ...
                [0, 1], ["converter:1"; "network-inverse"], ...
                "two-response-model-v1", zeros(2), ...
                repmat("resolved", 2, 2), [0; 0], [1, 1], evidence);

            testCase.verifyEqual(result.verificationStatus, ...
                "branch-verified-under-supplied-deviation-bounds");
        end

        function testExtremeFiniteScaleCannotProduceFalseVerification(testCase)
            magnitude = realmax;
            A = diag(magnitude*exp(1i*deg2rad([20, -100])));
            responses = {cat(3, A, A)};
            phase = computeStrictSectorialPhaseInterval(A);
            center = (phase.lowerPhase+phase.upperPhase)/2;
            evidence = testCase.evidence(deg2rad(40), 0);

            result = verifyHalfPlanePhaseBranchIntervals(responses, ...
                [0, 1], "converter:1", "analytic-test-model-v1", ...
                [center, center], ["resolved", "resolved"], ...
                center, 1, evidence);

            testCase.verifyEqual(result.verificationStatus, "indeterminate");
            testCase.verifyEqual(result.reasonCodes(2), ...
                "common-open-half-plane-not-verified");
            testCase.verifyTrue(all(isfinite( ...
                result.referenceAccretivityMarginNormalized), 'all'));
        end
    end

    methods (Static, Access=private)
        function value = evidence(theta, delta)
            frequencyCount = numel(theta)+1;
            value = struct( ...
                'responseDeviationUpperBound2Norm', delta, ...
                'rotationThetaRad', theta, ...
                'frequencyGridHz', 0:frequencyCount-1, ...
                'responseIds', "converter:1", ...
                'frequencyUnit', "Hz", ...
                'boundMethod', "analytic-test-bound", ...
                'modelHash', "analytic-test-model-v1", ...
                'referencePoint', "left-endpoint", ...
                'assuranceLevel', "double-precision-numerical-bound", ...
                'floatingPointCertified', false, ...
                'roundoffBoundIncluded', false, ...
                'independentVariable', "frequency", ...
                'derivativeUnit', "per-Hz");
        end
    end
end
