import assert from 'node:assert/strict';
import { sanitizeText, extractVisibleMessage } from './export_visible_conversation.mjs';

const record = (role, text, channel) => ({ type: 'response_item', payload: { type: 'message', role, channel, content: [{ type: 'input_text', text }] } });
assert.equal(extractVisibleMessage(record('assistant', 'private thoughts', 'analysis')), null);
const phased = record('assistant', 'private thoughts');
phased.payload.phase = 'analysis';
assert.equal(extractVisibleMessage(phased), null);
phased.payload.phase = 'final_answer';
assert.equal(extractVisibleMessage(phased).channel, 'final_answer');
assert.equal(extractVisibleMessage(record('developer', 'private instructions')), null);
assert.equal(extractVisibleMessage({ type: 'event_msg', payload: { type: 'agent_message', message: 'duplicate' } }), null);
assert.equal(extractVisibleMessage(record('user', '<environment_context>machine details</environment_context>')), null);
assert.equal(extractVisibleMessage(record('user', '# AGENTS.md instructions\n<INSTRUCTIONS>private</INSTRUCTIONS>')), null);
assert.equal(extractVisibleMessage(record('user', '<in-app-browser-context source="ambient-ui-state">machine details</in-app-browser-context>\n\n继续')).text, '继续');
assert.equal(extractVisibleMessage(record('assistant', '公开回复', 'final')).text, '公开回复');
assert.equal(extractVisibleMessage(record('assistant', '工作进展', 'commentary')).text, '工作进展');
assert.equal(extractVisibleMessage(record('assistant', 'reply<oai-mem-citation>internal registry</oai-mem-citation>', 'final')).text, 'reply');
assert.equal(extractVisibleMessage(record('user', '<send_user_message_question_reply>[{"question":"哪里？","answer":"画布"}]</send_user_message_question_reply>')).text, '问题：哪里？\n\n回答：画布');
assert.match(sanitizeText('C:\\Users\\Alice\\Documents\\file.md').text, /\[USER\]/);
assert.match(sanitizeText('wxid_example_123').text, /\[WECHAT_ID\]/);
assert.match(sanitizeText('sk-' + 'x'.repeat(32)).text, /\[REDACTED_TOKEN\]/);
assert.equal(sanitizeText('frequency 0.0211544371 Hz; 133 tests').text, 'frequency 0.0211544371 Hz; 133 tests');
assert.match(sanitizeText('api_key="' + 'x'.repeat(32) + '"').text, /\[REDACTED_SECRET\]/);
assert.match(sanitizeText('Bearer ' + 'x'.repeat(32)).text, /\[REDACTED_TOKEN\]/);
assert.match(sanitizeText('password="testpass"').text, /\[REDACTED_SECRET\]/);
assert.equal(sanitizeText('https://name:password@example.org').text, 'https://[REDACTED_AUTH]@example.org');
assert.equal(sanitizeText('-----BEGIN PRIVATE KEY-----\nsecret\n-----END PRIVATE KEY-----').text, '[REDACTED_PRIVATE_KEY]');
const image = record('user', '看看图片');
image.payload.content.push({ type: 'input_image', image_url: 'data:image/png;base64,PRIVATE' });
assert.equal(extractVisibleMessage(image).attachments, 1);
assert.ok(!extractVisibleMessage(image).text.includes('PRIVATE'));
console.log('Visible conversation export: privacy and scope assertions passed.');
