function result = analyzeHermitianGeometry(A, options)
%ANALYZEHERMITIANGEOMETRY Diagnose rotated-Hermitian range geometry.
%   RESULT = ANALYZEHERMITIANGEOMETRY(A) decomposes the complex square
%   matrix A as A = H + 1i*G, where H and G are Hermitian. It then uses
%   CLASSIFYNUMERICALRANGE to identify a candidate rotation angle and
%   resolves the minimum-eigenvalue direction at that angle.
%
%   The returned separation margin describes numerical-range geometry. It
%   is not a closed-loop stability margin. The contribution attribution is
%   marked as numerical-pending when the minimum eigenvalue is repeated or
%   the objective-value global-optimality envelope is too wide. The overall
%   numerical status is also pending when the numerical-range classifier
%   itself cannot certify a class.
%
%   RESULT = ANALYZEHERMITIANGEOMETRY(A, OPTIONS) accepts a scalar struct:
%       NumAngles                 - angular grid size, default 1440
%       RelTol                    - relative classification tolerance
%       AbsTol                    - absolute classification tolerance
%       Refine                    - local angle refinement, default true
%       RelativeEigenvalueGapTol  - direction gap threshold, default 1e-8
%       MaxNormalizedEnvelopeGap  - angular gap threshold, default 5e-3

    if nargin < 2 || isempty(options)
        options = struct();
    end

    options = validateOptions(options);
    classifierOptions = struct( ...
        'NumAngles', options.NumAngles, ...
        'RelTol', options.RelTol, ...
        'AbsTol', options.AbsTol, ...
        'Refine', options.Refine);
    classification = classifyNumericalRange(A, classifierOptions);

    A = double(A);
    hermitianPart = (A+A')/2;
    quadratureHermitianPart = (A-A')/(2i);
    scale = classification.scale;
    frobeniusScale = norm(A, 'fro');
    reconstructionScale = max(frobeniusScale, 1);
    reconstructionResidual = norm( ...
        A-(hermitianPart+1i*quadratureHermitianPart), 'fro') / ...
        reconstructionScale;
    commutator = hermitianPart*quadratureHermitianPart - ...
        quadratureHermitianPart*hermitianPart;
    commutatorScale = max(frobeniusScale^2, realmin('double'));
    normalizedCommutator = norm(commutator, 'fro')/commutatorScale;

    if classification.classification == "degenerate"
        result = makeDegenerateResult( ...
            classification, hermitianPart, quadratureHermitianPart, ...
            reconstructionResidual, normalizedCommutator);
        return;
    end

    theta = classification.theta;
    rotatedHermitianPart = cos(theta)*hermitianPart + ...
        sin(theta)*quadratureHermitianPart;
    rotatedHermitianPart = (rotatedHermitianPart+rotatedHermitianPart')/2;
    [eigenvectors, eigenvalueMatrix] = eig(rotatedHermitianPart, 'vector');
    [eigenvalues, order] = sort(real(eigenvalueMatrix), 'ascend');
    criticalDirection = canonicalizeDirection(eigenvectors(:, order(1)));
    minimumEigenvalue = eigenvalues(1);

    if isscalar(eigenvalues)
        eigenvalueGap = Inf;
    else
        eigenvalueGap = eigenvalues(2)-eigenvalues(1);
    end

    hermitianProjection = real(criticalDirection'*hermitianPart*criticalDirection);
    quadratureProjection = real( ...
        criticalDirection'*quadratureHermitianPart*criticalDirection);
    hermitianContribution = cos(theta)*hermitianProjection;
    quadratureContribution = sin(theta)*quadratureProjection;
    contributionResidual = abs(minimumEigenvalue - ...
        (hermitianContribution+quadratureContribution));
    normalizedEigenvalueGap = eigenvalueGap/scale;
    normalizedEnvelopeGap = classification.optimalityGap/scale;
    directionResolved = normalizedEigenvalueGap > ...
        options.RelativeEigenvalueGapTol;
    objectiveEnvelopeResolved = normalizedEnvelopeGap <= ...
        options.MaxNormalizedEnvelopeGap;
    isAttributionReliable = directionResolved && ...
        objectiveEnvelopeResolved;
    isDiagnosticResolved = classification.isCertified && ...
        isAttributionReliable;

    result = struct( ...
        'classification', classification, ...
        'hermitianPart', hermitianPart, ...
        'quadratureHermitianPart', quadratureHermitianPart, ...
        'reconstructionResidual', reconstructionResidual, ...
        'normalizedCommutator', normalizedCommutator, ...
        'theta', theta, ...
        'rotatedHermitianPart', rotatedHermitianPart, ...
        'criticalDirection', criticalDirection, ...
        'minimumEigenvalue', minimumEigenvalue, ...
        'normalizedSeparationMargin', minimumEigenvalue/scale, ...
        'hermitianProjection', hermitianProjection, ...
        'quadratureProjection', quadratureProjection, ...
        'hermitianContribution', hermitianContribution, ...
        'quadratureContribution', quadratureContribution, ...
        'normalizedHermitianContribution', hermitianContribution/scale, ...
        'normalizedQuadratureContribution', ...
            quadratureContribution/scale, ...
        'contributionResidual', contributionResidual, ...
        'eigenvalueGap', eigenvalueGap, ...
        'normalizedEigenvalueGap', normalizedEigenvalueGap, ...
        'normalizedEnvelopeGap', normalizedEnvelopeGap, ...
        'directionResolved', directionResolved, ...
        'objectiveEnvelopeResolved', objectiveEnvelopeResolved, ...
        'isAttributionReliable', isAttributionReliable, ...
        'classificationStatus', classification.classification, ...
        'attributionStatus', diagnosticStatus(isAttributionReliable), ...
        'overallNumericalStatus', ...
            diagnosticStatus(isDiagnosticResolved), ...
        'method', "rotated-Hermitian-critical-direction-v1");
end

function options = validateOptions(options)
    if ~(isstruct(options) && isscalar(options))
        error('gfm:analyzeHermitianGeometry:InvalidOptions', ...
            'Options must be a scalar struct.');
    end

    defaults = struct( ...
        'NumAngles', 1440, ...
        'RelTol', 1e-10, ...
        'AbsTol', 0, ...
        'Refine', true, ...
        'RelativeEigenvalueGapTol', 1e-8, ...
        'MaxNormalizedEnvelopeGap', 5e-3);
    optionNames = fieldnames(defaults);
    suppliedNames = fieldnames(options);
    unknownNames = setdiff(suppliedNames, optionNames);
    if ~isempty(unknownNames)
        error('gfm:analyzeHermitianGeometry:UnknownOption', ...
            'Unknown option: %s.', unknownNames{1});
    end

    for index = 1:numel(optionNames)
        name = optionNames{index};
        if ~isfield(options, name)
            options.(name) = defaults.(name);
        end
    end

    validatePositiveTolerance( ...
        options.RelativeEigenvalueGapTol, 'RelativeEigenvalueGapTol');
    validatePositiveTolerance( ...
        options.MaxNormalizedEnvelopeGap, 'MaxNormalizedEnvelopeGap');
end

function validatePositiveTolerance(value, name)
    if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
            isfinite(value) && value >= 0)
        error('gfm:analyzeHermitianGeometry:InvalidTolerance', ...
            '%s must be a finite nonnegative scalar.', name);
    end
end

function direction = canonicalizeDirection(direction)
    [~, pivot] = max(abs(direction));
    phase = angle(direction(pivot));
    direction = direction*exp(-1i*phase);
end

function status = diagnosticStatus(isReliable)
    if isReliable
        status = "resolved";
    else
        status = "numerical-pending";
    end
end

function result = makeDegenerateResult(classification, hermitianPart, ...
        quadratureHermitianPart, reconstructionResidual, ...
        normalizedCommutator)
    matrixSize = size(hermitianPart, 1);
    result = struct( ...
        'classification', classification, ...
        'hermitianPart', hermitianPart, ...
        'quadratureHermitianPart', quadratureHermitianPart, ...
        'reconstructionResidual', reconstructionResidual, ...
        'normalizedCommutator', normalizedCommutator, ...
        'theta', NaN, ...
        'rotatedHermitianPart', NaN(matrixSize), ...
        'criticalDirection', NaN(matrixSize, 1), ...
        'minimumEigenvalue', NaN, ...
        'normalizedSeparationMargin', NaN, ...
        'hermitianProjection', NaN, ...
        'quadratureProjection', NaN, ...
        'hermitianContribution', NaN, ...
        'quadratureContribution', NaN, ...
        'normalizedHermitianContribution', NaN, ...
        'normalizedQuadratureContribution', NaN, ...
        'contributionResidual', NaN, ...
        'eigenvalueGap', NaN, ...
        'normalizedEigenvalueGap', NaN, ...
        'normalizedEnvelopeGap', NaN, ...
        'directionResolved', false, ...
        'objectiveEnvelopeResolved', false, ...
        'isAttributionReliable', false, ...
        'classificationStatus', classification.classification, ...
        'attributionStatus', "numerical-pending", ...
        'overallNumericalStatus', "numerical-pending", ...
        'method', "rotated-Hermitian-critical-direction-v1");
end
