function result = buildMixedLoopShapingSamples(converterResponses, ...
        networkResponse, frequenciesHz, operatingPoints, ...
        weightingResponses, options)
%BUILDMIXEDLOOPSHAPINGSAMPLES Apply sampled dynamic loop shaping.
%   The implementation follows
%       E_i(s) = E_J,i,
%       C_i(s) = H_LPF(s) C_J,i,
%       F_i(s) = H_LPF(s) F_J,i + H_HPF(s) W_i(s) E_J,i^(-1).
%   Converter and network currents use opposite port directions, hence
%   +C for converters and -C for the network.

    if nargin < 6 || isempty(options)
        options = struct();
    end
    options = validateOptions(options);
    frequenciesHz = validateInputs(converterResponses, networkResponse, ...
        frequenciesHz, operatingPoints, weightingResponses);

    converterCount = numel(converterResponses);
    frequencyCount = numel(frequenciesHz);
    cutoffAngularFrequency = 2*pi*options.CutoffHz;
    lowPass = cutoffAngularFrequency ./ ...
        (1i*2*pi*frequenciesHz+cutoffAngularFrequency);
    highPass = 1-lowPass;

    shapedConverterResponses = cell(converterCount, 1);
    E = cell(converterCount, 1);
    C = cell(converterCount, 1);
    F = cell(converterCount, 1);
    transformationConditionNumbers = NaN(converterCount, frequencyCount);
    for converterIndex = 1:converterCount
        shapedConverterResponses{converterIndex} = ...
            complex(zeros(2, 2, frequencyCount));
        C{converterIndex} = complex(zeros(2, 2, frequencyCount));
        F{converterIndex} = complex(zeros(2, 2, frequencyCount));
        staticTransform = buildPowerPolarLinearization( ...
            operatingPoints{converterIndex});
        E{converterIndex} = staticTransform.E;
        for frequencyIndex = 1:frequencyCount
            C{converterIndex}(:, :, frequencyIndex) = ...
                lowPass(frequencyIndex)*staticTransform.C;
            highFrequencyFactor = ...
                weightingResponses{converterIndex}(:, :, frequencyIndex) / ...
                staticTransform.E;
            F{converterIndex}(:, :, frequencyIndex) = ...
                lowPass(frequencyIndex)*staticTransform.F + ...
                highPass(frequencyIndex)*highFrequencyFactor;
            shapedConverterResponses{converterIndex}(:, :, frequencyIndex) = ...
                (staticTransform.E*converterResponses{converterIndex}( ...
                    :, :, frequencyIndex) + ...
                C{converterIndex}(:, :, frequencyIndex)) * ...
                F{converterIndex}(:, :, frequencyIndex);
            transformationConditionNumbers( ...
                converterIndex, frequencyIndex) = cond( ...
                    F{converterIndex}(:, :, frequencyIndex), 2);
        end
    end

    shapedNetworkResponse = complex(zeros(size(networkResponse)));
    interconnectionResidual = NaN(1, frequencyCount);
    transformationStatus = strings(1, frequencyCount);
    reasonCodes = cell(1, frequencyCount);
    for frequencyIndex = 1:frequencyCount
        Eblock = blockDiagonalAt(E, 1);
        Cblock = blockDiagonalAt(C, frequencyIndex);
        Fblock = blockDiagonalAt(F, frequencyIndex);
        rawConverterBlock = blockDiagonalAt( ...
            converterResponses, frequencyIndex);
        shapedConverterBlock = blockDiagonalAt( ...
            shapedConverterResponses, frequencyIndex);
        shapedNetworkResponse(:, :, frequencyIndex) = ...
            (Eblock*networkResponse(:, :, frequencyIndex)-Cblock)*Fblock;
        expectedInterconnection = Eblock*(rawConverterBlock+ ...
            networkResponse(:, :, frequencyIndex))*Fblock;
        actualInterconnection = shapedConverterBlock+ ...
            shapedNetworkResponse(:, :, frequencyIndex);
        interconnectionResidual(frequencyIndex) = norm( ...
            actualInterconnection-expectedInterconnection, 'fro') / ...
            max(norm(expectedInterconnection, 'fro'), 1);

        illConditioned = any(~isfinite( ...
            transformationConditionNumbers(:, frequencyIndex))) || ...
            any(transformationConditionNumbers(:, frequencyIndex) > ...
                options.MaxTransformationConditionNumber);
        residualTooLarge = interconnectionResidual(frequencyIndex) > ...
            options.MaxInterconnectionResidual;
        if illConditioned || residualTooLarge
            transformationStatus(frequencyIndex) = "numerical-pending";
            reasons = strings(2, 1);
            reasonCount = 0;
            if illConditioned
                reasonCount = reasonCount+1;
                reasons(reasonCount) = "ill-conditioned-F";
            end
            if residualTooLarge
                reasonCount = reasonCount+1;
                reasons(reasonCount) = "interconnection-residual-too-large";
            end
            reasonCodes{frequencyIndex} = reasons(1:reasonCount);
        else
            transformationStatus(frequencyIndex) = ...
                "sampled-algebra-resolved";
            reasonCodes{frequencyIndex} = "sampled-algebra-resolved";
        end
    end

    result = struct( ...
        'converterResponses', {shapedConverterResponses}, ...
        'networkResponse', shapedNetworkResponse, ...
        'frequenciesHz', frequenciesHz, ...
        'lowPass', lowPass, ...
        'highPass', highPass, ...
        'E', {E}, ...
        'C', {C}, ...
        'F', {F}, ...
        'transformationConditionNumbers', ...
            transformationConditionNumbers, ...
        'interconnectionResidual', interconnectionResidual, ...
        'transformationStatus', transformationStatus, ...
        'reasonCodes', {reasonCodes}, ...
        'operatingPoints', {operatingPoints}, ...
        'conventionMetadata', options.ConventionMetadata, ...
        'dynamicPreconditionsStatus', "not-evaluated", ...
        'assessmentScope', "sampled-frequency-algebra", ...
        'options', options, ...
        'method', "mixed-loop-shaping-samples-v1");
end

function matrix = blockDiagonalAt(blocks, frequencyIndex)
    totalDimension = 0;
    for index = 1:numel(blocks)
        totalDimension = totalDimension+size(blocks{index}, 1);
    end
    matrix = complex(zeros(totalDimension));
    firstIndex = 1;
    for index = 1:numel(blocks)
        blockDimension = size(blocks{index}, 1);
        indices = firstIndex:(firstIndex+blockDimension-1);
        if ismatrix(blocks{index})
            matrix(indices, indices) = blocks{index};
        else
            matrix(indices, indices) = ...
                blocks{index}(:, :, frequencyIndex);
        end
        firstIndex = firstIndex+blockDimension;
    end
end

function frequenciesHz = validateInputs(converterResponses, ...
        networkResponse, frequenciesHz, operatingPoints, weightingResponses)
    if ~(iscell(converterResponses) && ~isempty(converterResponses) && ...
            iscell(operatingPoints) && iscell(weightingResponses) && ...
            numel(converterResponses) == numel(operatingPoints) && ...
            numel(converterResponses) == numel(weightingResponses))
        error('gfm:buildMixedLoopShapingSamples:InvalidConverterInputs', ...
            'Converter responses, operating points, and weights must align.');
    end
    if ~(isnumeric(frequenciesHz) && isreal(frequenciesHz) && ...
            isvector(frequenciesHz) && ~isempty(frequenciesHz) && ...
            all(isfinite(frequenciesHz)) && all(frequenciesHz >= 0))
        error('gfm:buildMixedLoopShapingSamples:InvalidFrequencies', ...
            'frequenciesHz must be a finite nonnegative real vector.');
    end
    frequenciesHz = double(frequenciesHz(:).');
    if any(diff(frequenciesHz) <= 0)
        error('gfm:buildMixedLoopShapingSamples:InvalidFrequencies', ...
            'frequenciesHz must be strictly increasing.');
    end
    frequencyCount = numel(frequenciesHz);
    converterCount = numel(converterResponses);
    for index = 1:converterCount
        validateResponse(converterResponses{index}, 2, frequencyCount, ...
            'converter');
        validateResponse(weightingResponses{index}, 2, frequencyCount, ...
            'weighting');
        buildPowerPolarLinearization(operatingPoints{index});
    end
    validateResponse(networkResponse, 2*converterCount, ...
        frequencyCount, 'network');
end

function validateResponse(response, expectedDimension, frequencyCount, name)
    if ~(isnumeric(response) && ...
            size(response, 1) == expectedDimension && ...
            size(response, 2) == expectedDimension && ...
            size(response, 3) == frequencyCount && ...
            all(isfinite(response(:))))
        error('gfm:buildMixedLoopShapingSamples:InvalidResponse', ...
            '%s response has an invalid size or nonfinite value.', name);
    end
end

function options = validateOptions(options)
    if ~(isstruct(options) && isscalar(options))
        error('gfm:buildMixedLoopShapingSamples:InvalidOptions', ...
            'options must be a scalar struct.');
    end
    defaults = struct( ...
        'CutoffHz', 0.5, ...
        'MaxTransformationConditionNumber', 1e12, ...
        'MaxInterconnectionResidual', 1e-10, ...
        'ConventionMetadata', {[]});
    names = fieldnames(defaults);
    unknownNames = setdiff(fieldnames(options), names);
    if ~isempty(unknownNames)
        error('gfm:buildMixedLoopShapingSamples:UnknownOption', ...
            'Unknown option: %s.', unknownNames{1});
    end
    for index = 1:numel(names)
        name = names{index};
        if ~isfield(options, name)
            options.(name) = defaults.(name);
        end
        if strcmp(name, 'ConventionMetadata')
            continue;
        end
        value = options.(name);
        if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
                isfinite(value) && value > 0)
            error('gfm:buildMixedLoopShapingSamples:InvalidOption', ...
                '%s must be a finite positive scalar.', name);
        end
    end
    options.ConventionMetadata = validateConventionMetadata( ...
        options.ConventionMetadata);
end

function metadata = validateConventionMetadata(metadata)
    if ~(isstruct(metadata) && isscalar(metadata))
        error('gfm:buildMixedLoopShapingSamples:InvalidConvention', ...
            'ConventionMetadata must be an explicit scalar struct.');
    end
    names = ["frameConventionId", "converterCurrentDirection", ...
        "networkCurrentDirection", "powerConvention"];
    if ~all(isfield(metadata, names))
        error('gfm:buildMixedLoopShapingSamples:InvalidConvention', ...
            'ConventionMetadata is missing a required field.');
    end
    textValues = string(struct2cell(metadata));
    if any(ismissing(textValues)) || any(strlength(textValues) == 0)
        error('gfm:buildMixedLoopShapingSamples:InvalidConvention', ...
            'ConventionMetadata does not match the supported port contract.');
    end
    frameId = string(metadata.frameConventionId);
    if frameId == "analytic-test-global-synchronous-dq-v1"
        expectedConverterDirection = "converter-to-network";
        expectedNetworkDirection = "network-to-converter";
        expectedPowerConvention = "injection-positive";
    elseif frameId == "cifelli-anta-author-global-synchronous-dq-v1"
        expectedConverterDirection = "network-to-converter";
        expectedNetworkDirection = "converter-to-network";
        expectedPowerConvention = "load-positive";
    else
        error('gfm:buildMixedLoopShapingSamples:InvalidConvention', ...
            'frameConventionId is not a supported versioned convention.');
    end
    if string(metadata.converterCurrentDirection) ~= ...
            expectedConverterDirection || ...
            string(metadata.networkCurrentDirection) ~= ...
            expectedNetworkDirection || ...
            string(metadata.powerConvention) ~= expectedPowerConvention
        error('gfm:buildMixedLoopShapingSamples:InvalidConvention', ...
            'ConventionMetadata does not match its frame convention.');
    end
end
