function result = evaluateMixedGainPhaseSamples(converterResponses, ...
        networkResponse, frequenciesHz, conventions, preconditions, options)
%EVALUATEMIXEDGAINPHASESAMPLES Evaluate sampled sufficient conditions.
%   This sampled API evaluates gain and seeded, frequency-continuous phase
%   coverage on the supplied grid. It never upgrades finite-grid evidence
%   to a theorem-level conclusion. Failure means only that this sufficient
%   condition did not confirm a point; it does not imply instability.

    if nargin < 6 || isempty(options)
        options = struct();
    end
    options = validateOptions(options);
    frequenciesHz = validateInputs(converterResponses, networkResponse, ...
        frequenciesHz, conventions, preconditions);

    converterCount = numel(converterResponses);
    frequencyCount = numel(frequenciesHz);
    phaseSeeds = validatePhaseSeeds(options.PhaseCenterSeeds, converterCount);

    converterMaximumSingularValue = NaN(converterCount, frequencyCount);
    networkMinimumSingularValue = NaN(1, frequencyCount);
    networkConditionNumber = NaN(1, frequencyCount);
    gainMargin = NaN(1, frequencyCount);
    gainStatus = strings(1, frequencyCount);

    converterRawLowerPhase = NaN(converterCount, frequencyCount);
    converterRawUpperPhase = NaN(converterCount, frequencyCount);
    converterRawPhaseStatus = strings(converterCount, frequencyCount);
    networkInverseRawLowerPhase = NaN(1, frequencyCount);
    networkInverseRawUpperPhase = NaN(1, frequencyCount);
    networkInverseRawPhaseStatus = strings(1, frequencyCount);

    identityMatrix = eye(size(networkResponse, 1));
    for frequencyIndex = 1:frequencyCount
        networkMatrix = networkResponse(:, :, frequencyIndex);
        networkSingularValues = svd(networkMatrix);
        networkMinimumSingularValue(frequencyIndex) = networkSingularValues(end);
        networkConditionNumber(frequencyIndex) = cond(networkMatrix, 2);

        for converterIndex = 1:converterCount
            converterMatrix = ...
                converterResponses{converterIndex}(:, :, frequencyIndex);
            converterSingularValues = svd(converterMatrix);
            converterMaximumSingularValue(converterIndex, frequencyIndex) = ...
                converterSingularValues(1);
            phaseResult = computeStrictSectorialPhaseInterval( ...
                converterMatrix, options.PhaseOptions);
            converterRawLowerPhase(converterIndex, frequencyIndex) = ...
                phaseResult.lowerPhase;
            converterRawUpperPhase(converterIndex, frequencyIndex) = ...
                phaseResult.upperPhase;
            converterRawPhaseStatus(converterIndex, frequencyIndex) = ...
                phaseResult.status;
        end

        maximumConverterGain = max( ...
            converterMaximumSingularValue(:, frequencyIndex));
        gainMargin(frequencyIndex) = ...
            networkMinimumSingularValue(frequencyIndex)-maximumConverterGain;
        gainScale = max(networkMinimumSingularValue(frequencyIndex), ...
            maximumConverterGain);
        gainTolerance = max(options.GainAbsTol, ...
            options.GainRelTol*gainScale);
        gainStatus(frequencyIndex) = classifySignedMargin( ...
            gainMargin(frequencyIndex), gainTolerance);

        if ~isfinite(networkConditionNumber(frequencyIndex)) || ...
                networkConditionNumber(frequencyIndex) > ...
                options.NetworkConditionNumberLimit
            networkInverseRawPhaseStatus(frequencyIndex) = ...
                "numerical-pending";
        else
            networkInverse = networkMatrix\identityMatrix;
            phaseResult = computeStrictSectorialPhaseInterval( ...
                networkInverse, options.PhaseOptions);
            networkInverseRawLowerPhase(frequencyIndex) = ...
                phaseResult.lowerPhase;
            networkInverseRawUpperPhase(frequencyIndex) = ...
                phaseResult.upperPhase;
            networkInverseRawPhaseStatus(frequencyIndex) = ...
                phaseResult.status;
        end
    end

    rawLowerPhase = [converterRawLowerPhase; networkInverseRawLowerPhase];
    rawUpperPhase = [converterRawUpperPhase; networkInverseRawUpperPhase];
    rawPhaseStatus = [converterRawPhaseStatus; ...
        networkInverseRawPhaseStatus];
    branchResult = unwrapPhaseIntervalSamples(rawLowerPhase, rawUpperPhase, ...
        rawPhaseStatus, [phaseSeeds.converterCenters; ...
        phaseSeeds.networkInverseCenter], options.PhaseBranchOptions);

    converterLowerPhase = branchResult.lowerPhase(1:converterCount, :);
    converterUpperPhase = branchResult.upperPhase(1:converterCount, :);
    networkInverseLowerPhase = branchResult.lowerPhase(end, :);
    networkInverseUpperPhase = branchResult.upperPhase(end, :);
    upperPhaseMargin = NaN(converterCount, frequencyCount);
    lowerPhaseMargin = NaN(converterCount, frequencyCount);
    converterPhaseSpreadMargin = NaN(1, frequencyCount);
    phaseStatus = strings(1, frequencyCount);
    sampleCoverage = strings(1, frequencyCount);
    activeConstraint = strings(1, frequencyCount);
    reasonCodes = cell(1, frequencyCount);

    for frequencyIndex = 1:frequencyCount
        [phaseStatus(frequencyIndex), ...
            upperPhaseMargin(:, frequencyIndex), ...
            lowerPhaseMargin(:, frequencyIndex), ...
            converterPhaseSpreadMargin(frequencyIndex), phaseReasons] = ...
            evaluateAlignedPhaseCondition( ...
                converterRawPhaseStatus(:, frequencyIndex), ...
                networkInverseRawPhaseStatus(frequencyIndex), ...
                branchResult.branchStatus(:, frequencyIndex), ...
                converterLowerPhase(:, frequencyIndex), ...
                converterUpperPhase(:, frequencyIndex), ...
                networkInverseLowerPhase(frequencyIndex), ...
                networkInverseUpperPhase(frequencyIndex), ...
                networkConditionNumber(frequencyIndex), options);
        [sampleCoverage(frequencyIndex), activeConstraint(frequencyIndex)] = ...
            combineConditions(gainStatus(frequencyIndex), ...
                phaseStatus(frequencyIndex));
        reasonCodes{frequencyIndex} = buildReasonCodes( ...
            gainStatus(frequencyIndex), phaseStatus(frequencyIndex), ...
            phaseReasons);
    end

    if any(sampleCoverage == "uncovered")
        sampledBandStatus = ...
            "not-covered-on-grid-under-phase-branch-assumption";
    elseif any(sampleCoverage == "indeterminate")
        sampledBandStatus = "indeterminate";
    elseif all(gainStatus == "pass")
        sampledBandStatus = "gain-covered-on-grid";
    else
        sampledBandStatus = ...
            "covered-on-grid-under-phase-branch-assumption";
    end

    preconditionValues = preconditionValueVector(preconditions);
    result = struct( ...
        'frequenciesHz', frequenciesHz, ...
        'converterMaximumSingularValue', converterMaximumSingularValue, ...
        'networkMinimumSingularValue', networkMinimumSingularValue, ...
        'networkConditionNumber', networkConditionNumber, ...
        'gainMargin', gainMargin, ...
        'gainStatus', gainStatus, ...
        'converterRawLowerPhase', converterRawLowerPhase, ...
        'converterRawUpperPhase', converterRawUpperPhase, ...
        'converterRawPhaseStatus', converterRawPhaseStatus, ...
        'networkInverseRawLowerPhase', networkInverseRawLowerPhase, ...
        'networkInverseRawUpperPhase', networkInverseRawUpperPhase, ...
        'networkInverseRawPhaseStatus', networkInverseRawPhaseStatus, ...
        'converterLowerPhase', converterLowerPhase, ...
        'converterUpperPhase', converterUpperPhase, ...
        'networkInverseLowerPhase', networkInverseLowerPhase, ...
        'networkInverseUpperPhase', networkInverseUpperPhase, ...
        'phaseBranchStatus', branchResult.branchStatus, ...
        'phaseBranchShiftTurns', branchResult.branchShiftTurns, ...
        'phaseBranchReasonCodes', branchResult.reasonCodes, ...
        'phaseBranchAssumptionStatus', branchResult.assumptionStatus, ...
        'phaseSeedProvenance', string(options.PhaseSeedProvenance), ...
        'upperPhaseMargin', upperPhaseMargin, ...
        'lowerPhaseMargin', lowerPhaseMargin, ...
        'converterPhaseSpreadMargin', converterPhaseSpreadMargin, ...
        'phaseStatus', phaseStatus, ...
        'sampleCoverage', sampleCoverage, ...
        'sampleCoverageScope', ...
            "finite-grid-screening-with-declared-phase-branch", ...
        'activeConstraint', activeConstraint, ...
        'reasonCodes', {reasonCodes}, ...
        'sampledBandStatus', sampledBandStatus, ...
        'theoremStatus', "not-evaluated-by-sampled-api", ...
        'preconditionDeclarationStatus', "complete", ...
        'declaredPreconditionsSatisfied', all(preconditionValues), ...
        'conventions', conventions, ...
        'preconditions', preconditions, ...
        'options', options, ...
        'method', "seeded-strict-sectorial-mixed-gain-phase-screening-v3", ...
        'interpretationBoundary', ...
            ['Phase coverage depends on a user seed and a nearest-neighbor ', ...
             'branch assumption; inter-sample winding is not excluded. ', ...
             'Finite-grid coverage is not a theorem-level certificate. ', ...
             'Not confirmed by this sufficient condition does not mean ', ...
             'that the closed-loop system is unstable.']);
end

function [status, upperMargin, lowerMargin, spreadMargin, reasons] = ...
        evaluateAlignedPhaseCondition(converterRawStatus, networkRawStatus, ...
        branchStatus, converterLower, converterUpper, networkLower, ...
        networkUpper, networkCondition, options)
    converterCount = numel(converterRawStatus);
    upperMargin = NaN(converterCount, 1);
    lowerMargin = NaN(converterCount, 1);
    spreadMargin = NaN;
    reasons = strings(0, 1);

    if ~isfinite(networkCondition) || ...
            networkCondition > options.NetworkConditionNumberLimit
        status = "indeterminate";
        reasons(end+1, 1) = "ill-conditioned-network";
        return;
    end
    if any(converterRawStatus == "not-applicable")
        status = "fail";
        reasons(end+1, 1) = "converter-nonsectorial";
        return;
    end
    if networkRawStatus == "not-applicable"
        status = "fail";
        reasons(end+1, 1) = "network-inverse-nonsectorial";
        return;
    end
    if any([converterRawStatus; networkRawStatus] ~= "resolved")
        status = "indeterminate";
        reasons(end+1, 1) = "sectoriality-or-phase-indeterminate";
        return;
    end
    if any(branchStatus ~= ...
            "resolved-under-nearest-neighbor-assumption")
        status = "indeterminate";
        reasons(end+1, 1) = "phase-branch-indeterminate";
        return;
    end

    upperMargin = pi-networkUpper-converterUpper;
    lowerMargin = converterLower+pi+networkLower;
    spreadMargin = pi-(max(converterUpper)-min(converterLower));
    allMargins = [upperMargin; lowerMargin; spreadMargin];
    if all(allMargins > options.PhaseAbsTol)
        status = "pass";
        reasons(end+1, 1) = "phase-pass";
    elseif any(allMargins < -options.PhaseAbsTol)
        status = "fail";
        if any(upperMargin < -options.PhaseAbsTol)
            reasons(end+1, 1) = "upper-phase-overlap";
        end
        if any(lowerMargin < -options.PhaseAbsTol)
            reasons(end+1, 1) = "lower-phase-overlap";
        end
        if spreadMargin < -options.PhaseAbsTol
            reasons(end+1, 1) = "converter-phase-spread-overlap";
        end
    else
        status = "indeterminate";
        reasons(end+1, 1) = "phase-boundary-indeterminate";
    end
end

function status = classifySignedMargin(margin, tolerance)
    if margin > tolerance
        status = "pass";
    elseif margin < -tolerance
        status = "fail";
    else
        status = "indeterminate";
    end
end

function [coverage, activeConstraint] = combineConditions( ...
        gainStatus, phaseStatus)
    if gainStatus == "pass" && phaseStatus == "pass"
        coverage = "both-pass";
        activeConstraint = "both";
    elseif gainStatus == "pass"
        coverage = "gain-pass";
        activeConstraint = "gain";
    elseif phaseStatus == "pass"
        coverage = "phase-pass";
        activeConstraint = "phase";
    elseif gainStatus == "fail" && phaseStatus == "fail"
        coverage = "uncovered";
        activeConstraint = "gain-and-phase";
    else
        coverage = "indeterminate";
        activeConstraint = "numerical-boundary-or-prerequisite";
    end
end

function reasons = buildReasonCodes(gainStatus, phaseStatus, phaseReasons)
    reasons = strings(0, 1);
    if gainStatus == "indeterminate"
        reasons(end+1, 1) = "gain-boundary-indeterminate";
    else
        reasons(end+1, 1) = "gain-"+gainStatus;
    end
    if isempty(phaseReasons)
        reasons(end+1, 1) = "phase-"+phaseStatus;
    else
        reasons = [reasons; phaseReasons(:)];
    end
end

function frequenciesHz = validateInputs(converterResponses, ...
        networkResponse, frequenciesHz, conventions, preconditions)
    if ~(iscell(converterResponses) && ~isempty(converterResponses))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConverters', ...
            'converterResponses must be a nonempty cell array.');
    end
    if ~(isnumeric(frequenciesHz) && isreal(frequenciesHz) && ...
            isvector(frequenciesHz) && ~isempty(frequenciesHz) && ...
            all(isfinite(frequenciesHz)) && all(frequenciesHz >= 0))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidFrequencies', ...
            'frequenciesHz must be a finite nonnegative real vector.');
    end
    frequenciesHz = frequenciesHz(:).';
    if any(diff(frequenciesHz) <= 0)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidFrequencies', ...
            'frequenciesHz must be strictly increasing.');
    end
    frequencyCount = numel(frequenciesHz);

    converterDimension = 0;
    for index = 1:numel(converterResponses)
        response = converterResponses{index};
        validateResponseArray(response, frequencyCount, 'converter');
        converterDimension = converterDimension+size(response, 1);
    end
    validateResponseArray(networkResponse, frequencyCount, 'network');
    if size(networkResponse, 1) ~= converterDimension
        error('gfm:evaluateMixedGainPhaseSamples:DimensionMismatch', ...
            'Network dimension must equal the sum of converter dimensions.');
    end
    validateConventions(conventions);
    validatePreconditions(preconditions);
end

function validateResponseArray(response, frequencyCount, name)
    if ~(isnumeric(response) && ~isempty(response) && ...
            size(response, 1) == size(response, 2) && ...
            size(response, 3) == frequencyCount && ...
            all(isfinite(response(:))))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidResponse', ...
            '%s response must be a finite square matrix array.', name);
    end
end

function validateConventions(conventions)
    if ~(isstruct(conventions) && isscalar(conventions))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConventions', ...
            'conventions must be a scalar struct.');
    end
    requiredNames = ["frameConventionId", "currentDirection", ...
        "powerDirection", "sBase", "vBase", "fBase", ...
        "matrixType", "globalFrameId"];
    if ~all(isfield(conventions, requiredNames))
        error('gfm:evaluateMixedGainPhaseSamples:MissingConvention', ...
            'All coordinate, direction, base, and matrix conventions are required.');
    end
    if ~isTextScalar(conventions.frameConventionId)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConvention', ...
            'frameConventionId is not a supported versioned convention.');
    end
    if ~(isTextScalar(conventions.globalFrameId) && ...
            strlength(string(conventions.globalFrameId)) > 0)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConvention', ...
            'globalFrameId must be a nonempty text scalar.');
    end
    frameId = string(conventions.frameConventionId);
    if frameId == "analytic-test-global-synchronous-dq-v1"
        expectedCurrentDirection = "converter-to-network";
        expectedPowerDirection = "injection-positive";
    elseif frameId == "cifelli-anta-author-global-synchronous-dq-v1"
        expectedCurrentDirection = "network-to-converter";
        expectedPowerDirection = "load-positive";
    else
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConvention', ...
            'frameConventionId is not a supported versioned convention.');
    end
    validateExactText(conventions.currentDirection, ...
        expectedCurrentDirection, 'currentDirection');
    validateExactText(conventions.powerDirection, ...
        expectedPowerDirection, 'powerDirection');
    validateExactText(conventions.matrixType, "admittance", 'matrixType');
    baseNames = ["sBase", "vBase", "fBase"];
    for index = 1:numel(baseNames)
        value = conventions.(baseNames(index));
        if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
                isfinite(value) && value > 0)
            error('gfm:evaluateMixedGainPhaseSamples:InvalidConvention', ...
                '%s must be a finite positive scalar.', baseNames(index));
        end
    end
end

function validateExactText(value, expected, name)
    if ~(isTextScalar(value) && string(value) == expected)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidConvention', ...
            '%s must equal %s.', name, expected);
    end
end

function tf = isTextScalar(value)
    tf = (isstring(value) && isscalar(value) && ~ismissing(value)) || ...
        (ischar(value) && isrow(value));
end

function validatePreconditions(preconditions)
    if ~(isstruct(preconditions) && isscalar(preconditions))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidPreconditions', ...
            'preconditions must be a scalar struct.');
    end
    names = theoremPreconditionNames();
    if ~all(isfield(preconditions, names))
        error('gfm:evaluateMixedGainPhaseSamples:MissingPrecondition', ...
            'All theorem preconditions must be explicitly supplied.');
    end
    for index = 1:numel(names)
        value = preconditions.(names(index));
        if ~(islogical(value) && isscalar(value))
            error('gfm:evaluateMixedGainPhaseSamples:InvalidPrecondition', ...
                '%s must be a logical scalar.', names(index));
        end
    end
end

function values = preconditionValueVector(preconditions)
    names = theoremPreconditionNames();
    values = false(size(names));
    for index = 1:numel(names)
        values(index) = preconditions.(names(index));
    end
end

function names = theoremPreconditionNames()
    names = ["openLoopStable", "realRationalProper", ...
        "transformationWellDefined", "networkInverseStable", ...
        "noRhpCancellation", "endpointsCovered", ...
        "fullFrequencyCoverage"];
end

function options = validateOptions(options)
    if ~(isstruct(options) && isscalar(options))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidOptions', ...
            'options must be a scalar struct.');
    end
    defaults = struct( ...
        'GainRelTol', 1e-10, ...
        'GainAbsTol', 0, ...
        'PhaseAbsTol', 1e-10, ...
        'NetworkConditionNumberLimit', 1e12, ...
        'PhaseOptions', struct(), ...
        'PhaseCenterSeeds', struct( ...
            'converterCenters', [], 'networkInverseCenter', NaN), ...
        'PhaseBranchOptions', struct(), ...
        'PhaseSeedProvenance', "unspecified-user-declaration");
    names = fieldnames(defaults);
    unknownNames = setdiff(fieldnames(options), names);
    if ~isempty(unknownNames)
        error('gfm:evaluateMixedGainPhaseSamples:UnknownOption', ...
            'Unknown option: %s.', unknownNames{1});
    end
    for index = 1:numel(names)
        name = names{index};
        if ~isfield(options, name)
            options.(name) = defaults.(name);
        end
    end
    validateNonnegativeOption(options.GainRelTol, 'GainRelTol');
    validateNonnegativeOption(options.GainAbsTol, 'GainAbsTol');
    validateNonnegativeOption(options.PhaseAbsTol, 'PhaseAbsTol');
    if ~isTextScalar(options.PhaseSeedProvenance) || ...
            strlength(string(options.PhaseSeedProvenance)) == 0
        error('gfm:evaluateMixedGainPhaseSamples:InvalidOption', ...
            'PhaseSeedProvenance must be a nonempty text scalar.');
    end
    if ~(isnumeric(options.NetworkConditionNumberLimit) && ...
            isreal(options.NetworkConditionNumberLimit) && ...
            isscalar(options.NetworkConditionNumberLimit) && ...
            isfinite(options.NetworkConditionNumberLimit) && ...
            options.NetworkConditionNumberLimit > 0)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidOption', ...
            'NetworkConditionNumberLimit must be positive and finite.');
    end
end

function seeds = validatePhaseSeeds(seeds, converterCount)
    if ~(isstruct(seeds) && isscalar(seeds) && ...
            all(isfield(seeds, ["converterCenters", ...
                "networkInverseCenter"])))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidPhaseSeeds', ...
            'PhaseCenterSeeds must declare converter and network seeds.');
    end
    if isempty(seeds.converterCenters)
        seeds.converterCenters = NaN(converterCount, 1);
    end
    if ~(isnumeric(seeds.converterCenters) && ...
            isreal(seeds.converterCenters) && ...
            isvector(seeds.converterCenters) && ...
            numel(seeds.converterCenters) == converterCount && ...
            all(isfinite(seeds.converterCenters) | ...
                isnan(seeds.converterCenters)))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidPhaseSeeds', ...
            'One finite or NaN converter phase seed is required per converter.');
    end
    if ~(isnumeric(seeds.networkInverseCenter) && ...
            isreal(seeds.networkInverseCenter) && ...
            isscalar(seeds.networkInverseCenter) && ...
            (isfinite(seeds.networkInverseCenter) || ...
                isnan(seeds.networkInverseCenter)))
        error('gfm:evaluateMixedGainPhaseSamples:InvalidPhaseSeeds', ...
            'networkInverseCenter must be a finite scalar or NaN.');
    end
    seeds.converterCenters = seeds.converterCenters(:);
end

function validateNonnegativeOption(value, name)
    if ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
            isfinite(value) && value >= 0)
        error('gfm:evaluateMixedGainPhaseSamples:InvalidOption', ...
            '%s must be finite and nonnegative.', name);
    end
end
