function result = refineMixedGainPhaseFrequencyGrid(modelEvaluator, ...
        initialGridHz, conventions, preconditions, options)
%REFINEMIXEDGAINPHASEFREQUENCYGRID Refine a model-level frequency grid.
%   MODELEVALUATOR(FREQUENCIESHZ) must return a scalar struct containing
%   converterResponses and networkResponse for the requested frequencies.
%   Adaptive sampling improves numerical screening but does not, by itself,
%   prove the absence of inter-sample phase winding. An optional evaluator
%   can supply model-level deviation-bound evidence for interval checks.

    if nargin < 5 || isempty(options)
        options = struct();
    end
    options = validateOptions(options);
    frequenciesHz = validateInputs(modelEvaluator, initialGridHz);
    history = repmat(struct('iteration', [], 'frequencyPointCount', [], ...
        'sampledBandStatus', "", 'phaseBranchVerificationStatus', ""), ...
        1, options.MaxIterations+1);
    stopReason = "maximum-iterations-reached";
    verification = [];

    for iteration = 0:options.MaxIterations
        modelSamples = modelEvaluator(frequenciesHz);
        validateModelSamples(modelSamples);
        evaluation = evaluateMixedGainPhaseSamples( ...
            modelSamples.converterResponses, modelSamples.networkResponse, ...
            frequenciesHz, conventions, preconditions, ...
            options.EvaluationOptions);
        verification = evaluateHalfPlaneEvidence(evaluation, modelSamples, ...
            frequenciesHz, options);
        history(iteration+1) = struct( ...
            'iteration', iteration, ...
            'frequencyPointCount', numel(frequenciesHz), ...
            'sampledBandStatus', evaluation.sampledBandStatus, ...
            'phaseBranchVerificationStatus', ...
                verification.verificationStatus);

        if verification.verificationStatus == ...
                "branch-verified-under-supplied-deviation-bounds"
            stopReason = ...
                "all-phase-branches-verified-under-supplied-bounds";
            break;
        end
        if iteration == options.MaxIterations
            break;
        end
        if 2*numel(frequenciesHz)-1 > options.MaxFrequencyPoints
            stopReason = "maximum-frequency-points-reached";
            break;
        end
        frequenciesHz = insertIntervalMidpoints(frequenciesHz);
    end
    history = history(1:iteration+1);

    if verification.verificationStatus == ...
            "branch-verified-under-supplied-deviation-bounds"
        refinementStatus = ...
            "phase-branches-verified-under-supplied-bounds";
    else
        refinementStatus = "refined-screening-only";
    end
    result = struct( ...
        'frequenciesHz', frequenciesHz, ...
        'evaluation', evaluation, ...
        'phaseBranchVerification', verification, ...
        'refinementStatus', refinementStatus, ...
        'stopReason', stopReason, ...
        'iterationsCompleted', iteration, ...
        'frequencyPointCount', numel(frequenciesHz), ...
        'history', history, ...
        'method', "model-level-adaptive-frequency-refinement-v1", ...
        'theoremStatus', "not-evaluated-by-adaptive-sampling-api", ...
        'interpretationBoundary', ...
            ['Grid refinement can reveal missed behavior but cannot exclude ', ...
             'inter-sample winding without model-level response-deviation ', ...
             'bounds. Sufficient-condition failure does not imply instability.']);
end

function verification = evaluateHalfPlaneEvidence(evaluation, modelSamples, ...
        frequenciesHz, options)
    rawCenter = [(evaluation.converterRawLowerPhase+ ...
        evaluation.converterRawUpperPhase)/2; ...
        (evaluation.networkInverseRawLowerPhase+ ...
        evaluation.networkInverseRawUpperPhase)/2];
    rawStatus = [evaluation.converterRawPhaseStatus; ...
        evaluation.networkInverseRawPhaseStatus];
    seeds = options.EvaluationOptions.PhaseCenterSeeds;
    phaseCenterSeeds = [seeds.converterCenters(:); ...
        seeds.networkInverseCenter];
    seedFrequencyIndices = ones(numel(phaseCenterSeeds), 1);
    if isfield(options.EvaluationOptions, 'PhaseBranchOptions') && ...
            isfield(options.EvaluationOptions.PhaseBranchOptions, ...
                'SeedFrequencyIndices') && ...
            ~isempty(options.EvaluationOptions.PhaseBranchOptions. ...
                SeedFrequencyIndices)
        seedFrequencyIndices = options.EvaluationOptions. ...
            PhaseBranchOptions.SeedFrequencyIndices(:);
    end
    intervalCount = numel(frequenciesHz)-1;
    converterCount = numel(modelSamples.converterResponses);
    responseSamples = modelSamples.converterResponses(:);
    responseIds = "converter:"+(1:converterCount).';
    networkInverse = zeros(size(modelSamples.networkResponse));
    identity = eye(size(networkInverse, 1));
    networkConditionNumberLimit = 1e12;
    if isfield(options.EvaluationOptions, 'NetworkConditionNumberLimit')
        networkConditionNumberLimit = ...
            options.EvaluationOptions.NetworkConditionNumberLimit;
    end
    for index = 1:numel(frequenciesHz)
        if evaluation.networkConditionNumber(index) > ...
                networkConditionNumberLimit || ...
                ~isfinite(evaluation.networkConditionNumber(index))
            networkInverse(:, :, index) = NaN(size(identity));
        else
            networkInverse(:, :, index) = ...
                modelSamples.networkResponse(:, :, index)\identity;
        end
    end
    responseSamples{converterCount+1, 1} = networkInverse;
    responseIds(converterCount+1, 1) = "network-inverse";

    if isempty(options.VariationBoundEvaluator)
        evidence = struct( ...
            'responseDeviationUpperBound2Norm', ...
                NaN(converterCount+1, intervalCount), ...
            'rotationThetaRad', NaN(converterCount+1, intervalCount), ...
            'frequencyGridHz', frequenciesHz, ...
            'responseIds', responseIds, ...
            'frequencyUnit', "Hz", ...
            'boundMethod', "unavailable", ...
            'modelHash', string(modelSamples.modelHash), ...
            'referencePoint', "left-endpoint", ...
            'assuranceLevel', "double-precision-numerical-bound", ...
            'floatingPointCertified', false, ...
            'roundoffBoundIncluded', false, ...
            'independentVariable', "frequency", ...
            'derivativeUnit', "per-Hz");
    else
        evidence = options.VariationBoundEvaluator( ...
            frequenciesHz, modelSamples);
        if ~(isstruct(evidence) && isscalar(evidence))
            error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidBoundResult', ...
                'VariationBoundEvaluator must return an evidence struct.');
        end
    end
    branchVerificationOptions = options.BranchVerificationOptions;
    if isfield(options.EvaluationOptions, 'PhaseOptions')
        branchVerificationOptions.PhaseOptions = ...
            options.EvaluationOptions.PhaseOptions;
    end
    verification = verifyHalfPlanePhaseBranchIntervals(responseSamples, ...
        frequenciesHz, responseIds, modelSamples.modelHash, rawCenter, ...
        rawStatus, phaseCenterSeeds, seedFrequencyIndices, evidence, ...
        branchVerificationOptions);
end

function frequenciesHz = insertIntervalMidpoints(frequenciesHz)
    left = frequenciesHz(1:end-1);
    right = frequenciesHz(2:end);
    midpoint = (left+right)/2;
    positive = left > 0;
    midpoint(positive) = sqrt(left(positive).*right(positive));
    refined = [frequenciesHz; frequenciesHz];
    refined = refined(1:end-1);
    refined(2:2:end) = midpoint;
    frequenciesHz = refined;
end

function frequenciesHz = validateInputs(modelEvaluator, initialGridHz)
    if ~isa(modelEvaluator, 'function_handle')
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidEvaluator', ...
            'modelEvaluator must be a function handle.');
    end
    if ~(isnumeric(initialGridHz) && isreal(initialGridHz) && ...
            isvector(initialGridHz) && numel(initialGridHz) >= 2 && ...
            all(isfinite(initialGridHz)) && all(initialGridHz >= 0))
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidGrid', ...
            'initialGridHz must contain at least two finite nonnegative values.');
    end
    frequenciesHz = initialGridHz(:).';
    if any(diff(frequenciesHz) <= 0)
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidGrid', ...
            'initialGridHz must be strictly increasing.');
    end
end

function validateModelSamples(modelSamples)
    if ~(isstruct(modelSamples) && isscalar(modelSamples) && ...
            isfield(modelSamples, 'converterResponses') && ...
            isfield(modelSamples, 'networkResponse') && ...
            isfield(modelSamples, 'modelHash') && ...
            strlength(string(modelSamples.modelHash)) > 0)
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidModelSamples', ...
            ['modelEvaluator must return converterResponses, ', ...
             'networkResponse, and modelHash fields.']);
    end
end

function options = validateOptions(options)
    defaults = struct( ...
        'MaxIterations', 4, ...
        'MaxFrequencyPoints', 4097, ...
        'EvaluationOptions', struct(), ...
        'VariationBoundEvaluator', [], ...
        'BranchVerificationOptions', struct());
    if ~(isstruct(options) && isscalar(options))
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidOptions', ...
            'options must be a scalar struct.');
    end
    unknown = setdiff(fieldnames(options), fieldnames(defaults));
    if ~isempty(unknown)
        error('gfm:refineMixedGainPhaseFrequencyGrid:UnknownOption', ...
            'Unknown option: %s.', unknown{1});
    end
    names = fieldnames(defaults);
    for index = 1:numel(names)
        if ~isfield(options, names{index})
            options.(names{index}) = defaults.(names{index});
        end
    end
    if ~(isnumeric(options.MaxIterations) && ...
            isscalar(options.MaxIterations) && ...
            isfinite(options.MaxIterations) && options.MaxIterations >= 0 && ...
            options.MaxIterations == floor(options.MaxIterations))
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidOption', ...
            'MaxIterations must be a nonnegative integer.');
    end
    if ~(isnumeric(options.MaxFrequencyPoints) && ...
            isscalar(options.MaxFrequencyPoints) && ...
            isfinite(options.MaxFrequencyPoints) && ...
            options.MaxFrequencyPoints >= 2 && ...
            options.MaxFrequencyPoints == floor(options.MaxFrequencyPoints))
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidOption', ...
            'MaxFrequencyPoints must be an integer no smaller than two.');
    end
    if ~(isempty(options.VariationBoundEvaluator) || ...
            isa(options.VariationBoundEvaluator, 'function_handle'))
        error('gfm:refineMixedGainPhaseFrequencyGrid:InvalidOption', ...
            'VariationBoundEvaluator must be empty or a function handle.');
    end
    if ~(isstruct(options.EvaluationOptions) && ...
            isscalar(options.EvaluationOptions) && ...
            isfield(options.EvaluationOptions, 'PhaseCenterSeeds'))
        error('gfm:refineMixedGainPhaseFrequencyGrid:MissingPhaseSeeds', ...
            'EvaluationOptions must contain explicit PhaseCenterSeeds.');
    end
end
