function result = unwrapPhaseIntervalSamples(lowerPhase, upperPhase, ...
        rawStatus, phaseCenterSeeds, options)
%UNWRAPPHASEINTERVALSAMPLES Track matrix-phase branches over frequency.
%   Each row represents one transfer-matrix response and each column one
%   increasing frequency sample. The first resolved segment is anchored by
%   an explicit phase-center seed. Later centers are shifted by integer
%   multiples of 2*pi to remain continuous. A gap in resolved phase data or
%   an excessive center step makes the later branch indeterminate.

    if nargin < 5 || isempty(options)
        options = struct();
    end
    options = validateOptions(options);
    validateInputs(lowerPhase, upperPhase, rawStatus, phaseCenterSeeds);

    responseCount = size(lowerPhase, 1);
    frequencyCount = size(lowerPhase, 2);
    options.SeedFrequencyIndices = normalizeSeedFrequencyIndices( ...
        options.SeedFrequencyIndices, responseCount, frequencyCount);
    alignedLowerPhase = NaN(size(lowerPhase));
    alignedUpperPhase = NaN(size(upperPhase));
    alignedCenter = NaN(size(lowerPhase));
    branchShiftTurns = NaN(size(lowerPhase));
    branchStatus = strings(size(rawStatus));
    reasonCodes = strings(size(rawStatus));

    for responseIndex = 1:responseCount
        previousCenter = phaseCenterSeeds(responseIndex);
        continuityBroken = false;
        seedFrequencyIndex = options.SeedFrequencyIndices(responseIndex);
        for frequencyIndex = 1:frequencyCount
            if frequencyIndex < seedFrequencyIndex
                branchStatus(responseIndex, frequencyIndex) = ...
                    "phase-branch-indeterminate";
                reasonCodes(responseIndex, frequencyIndex) = ...
                    "phase-before-explicit-seed";
                continue;
            end
            if rawStatus(responseIndex, frequencyIndex) ~= "resolved"
                branchStatus(responseIndex, frequencyIndex) = ...
                    "phase-unavailable";
                reasonCodes(responseIndex, frequencyIndex) = ...
                    "raw-phase-unavailable";
                continuityBroken = true;
                continue;
            end
            if ~isfinite(previousCenter)
                branchStatus(responseIndex, frequencyIndex) = ...
                    "phase-branch-indeterminate";
                reasonCodes(responseIndex, frequencyIndex) = ...
                    "phase-branch-unanchored";
                continuityBroken = true;
                continue;
            end
            if continuityBroken
                branchStatus(responseIndex, frequencyIndex) = ...
                    "phase-branch-indeterminate";
                reasonCodes(responseIndex, frequencyIndex) = ...
                    "phase-gap-indeterminate";
                continue;
            end

            rawCenter = (lowerPhase(responseIndex, frequencyIndex)+ ...
                upperPhase(responseIndex, frequencyIndex))/2;
            shiftTurns = round((previousCenter-rawCenter)/(2*pi));
            candidateCenter = rawCenter+2*pi*shiftTurns;
            centerStep = candidateCenter-previousCenter;
            if abs(centerStep) >= options.MaxCenterStep- ...
                    options.StepBoundaryTolerance
                branchStatus(responseIndex, frequencyIndex) = ...
                    "phase-branch-indeterminate";
                reasonCodes(responseIndex, frequencyIndex) = ...
                    "phase-step-indeterminate";
                continuityBroken = true;
                continue;
            end

            alignedLowerPhase(responseIndex, frequencyIndex) = ...
                lowerPhase(responseIndex, frequencyIndex)+2*pi*shiftTurns;
            alignedUpperPhase(responseIndex, frequencyIndex) = ...
                upperPhase(responseIndex, frequencyIndex)+2*pi*shiftTurns;
            alignedCenter(responseIndex, frequencyIndex) = candidateCenter;
            branchShiftTurns(responseIndex, frequencyIndex) = shiftTurns;
            branchStatus(responseIndex, frequencyIndex) = ...
                "resolved-under-nearest-neighbor-assumption";
            reasonCodes(responseIndex, frequencyIndex) = ...
                "phase-branch-resolved-under-nearest-neighbor-assumption";
            previousCenter = candidateCenter;
        end
    end

    result = struct( ...
        'lowerPhase', alignedLowerPhase, ...
        'upperPhase', alignedUpperPhase, ...
        'center', alignedCenter, ...
        'branchShiftTurns', branchShiftTurns, ...
        'branchStatus', branchStatus, ...
        'reasonCodes', reasonCodes, ...
        'phaseCenterSeeds', phaseCenterSeeds(:), ...
        'options', options, ...
        'scope', "sampled-frequency-branch-screening", ...
        'assumptionStatus', ...
            "user-seeded-nearest-neighbor-without-inter-sample-proof", ...
        'method', "seeded-nearest-2pi-branch-assumption-v2");
end

function validateInputs(lowerPhase, upperPhase, rawStatus, phaseCenterSeeds)
    if ~(isnumeric(lowerPhase) && isreal(lowerPhase) && ...
            ismatrix(lowerPhase) && ...
            isnumeric(upperPhase) && isreal(upperPhase) && ...
            ismatrix(upperPhase) && ...
            isequal(size(lowerPhase), size(upperPhase)) && ...
            ~isempty(lowerPhase))
        error('gfm:unwrapPhaseIntervalSamples:InvalidIntervals', ...
            'lowerPhase and upperPhase must be same-size real arrays.');
    end
    if ~(isstring(rawStatus) && isequal(size(rawStatus), size(lowerPhase)))
        error('gfm:unwrapPhaseIntervalSamples:InvalidStatus', ...
            'rawStatus must be a same-size string array.');
    end
    if ~(isnumeric(phaseCenterSeeds) && isreal(phaseCenterSeeds) && ...
            isvector(phaseCenterSeeds) && ...
            numel(phaseCenterSeeds) == size(lowerPhase, 1) && ...
            all(isfinite(phaseCenterSeeds) | isnan(phaseCenterSeeds)))
        error('gfm:unwrapPhaseIntervalSamples:InvalidSeeds', ...
            'One finite or NaN phase-center seed is required per row.');
    end
    resolved = rawStatus == "resolved";
    if any(~isfinite(lowerPhase(resolved))) || ...
            any(~isfinite(upperPhase(resolved))) || ...
            any(lowerPhase(resolved) > upperPhase(resolved))
        error('gfm:unwrapPhaseIntervalSamples:InvalidIntervals', ...
            'Resolved raw intervals must be finite and ordered.');
    end
end

function options = validateOptions(options)
    if ~(isstruct(options) && isscalar(options))
        error('gfm:unwrapPhaseIntervalSamples:InvalidOptions', ...
            'options must be a scalar struct.');
    end
    defaults = struct( ...
        'MaxCenterStep', 0.9*pi, ...
        'StepBoundaryTolerance', 1e-8, ...
        'SeedFrequencyIndices', {[]});
    names = fieldnames(defaults);
    unknownNames = setdiff(fieldnames(options), names);
    if ~isempty(unknownNames)
        error('gfm:unwrapPhaseIntervalSamples:UnknownOption', ...
            'Unknown option: %s.', unknownNames{1});
    end
    for index = 1:numel(names)
        name = names{index};
        if ~isfield(options, name)
            options.(name) = defaults.(name);
        end
    end
    if ~(isempty(options.SeedFrequencyIndices) || ...
            (isnumeric(options.SeedFrequencyIndices) && ...
            isreal(options.SeedFrequencyIndices) && ...
            isvector(options.SeedFrequencyIndices) && ...
            all(isfinite(options.SeedFrequencyIndices)) && ...
            all(options.SeedFrequencyIndices == ...
                floor(options.SeedFrequencyIndices))))
        error('gfm:unwrapPhaseIntervalSamples:InvalidOption', ...
            'SeedFrequencyIndices must contain finite integer indices.');
    end
    if ~(isnumeric(options.MaxCenterStep) && ...
            isreal(options.MaxCenterStep) && isscalar(options.MaxCenterStep) && ...
            isfinite(options.MaxCenterStep) && options.MaxCenterStep > 0 && ...
            options.MaxCenterStep < pi)
        error('gfm:unwrapPhaseIntervalSamples:InvalidOption', ...
            'MaxCenterStep must be a finite scalar strictly between 0 and pi.');
    end
    if ~(isnumeric(options.StepBoundaryTolerance) && ...
            isreal(options.StepBoundaryTolerance) && ...
            isscalar(options.StepBoundaryTolerance) && ...
            isfinite(options.StepBoundaryTolerance) && ...
            options.StepBoundaryTolerance >= 0 && ...
            options.StepBoundaryTolerance < options.MaxCenterStep)
        error('gfm:unwrapPhaseIntervalSamples:InvalidOption', ...
            'StepBoundaryTolerance must be finite and smaller than MaxCenterStep.');
    end
end

function indices = normalizeSeedFrequencyIndices( ...
        indices, responseCount, frequencyCount)
    if isempty(indices)
        indices = ones(responseCount, 1);
    end
    if ~(isvector(indices) && numel(indices) == responseCount && ...
            all(indices >= 1) && all(indices <= frequencyCount))
        error('gfm:unwrapPhaseIntervalSamples:InvalidOption', ...
            ['SeedFrequencyIndices must provide one in-range index ', ...
             'per response.']);
    end
    indices = indices(:);
end
