function result = verifyHalfPlanePhaseBranchIntervals(responseSamples, ...
        frequenciesHz, responseIds, expectedModelHash, rawCenter, rawStatus, ...
        phaseCenterSeeds, seedFrequencyIndices, evidence, options)
%VERIFYHALFPLANEPHASEBRANCHINTERVALS Verify matrix-phase branches on intervals.
%   For every adjacent frequency interval, EVIDENCE supplies a declared
%   two-norm bound delta on the response deviation from the left endpoint
%   and a rotation theta. The function recomputes
%       mu = lambda_min(He(exp(-1i*theta)*A_left))
%   and checks mu-delta > tolerance. Under the supplied deviation bound,
%   this confines the numerical range to
%   one common open half-plane throughout the interval and excludes hidden
%   whole-turn phase winding. The deviation bound itself remains an
%   external model-level obligation and is recorded with its method/hash.

    if nargin < 10 || isempty(options)
        options = struct();
    end
    options = validateOptions(options);
    [responseCount, frequencyCount, evidence] = validateInputs( ...
        responseSamples, frequenciesHz, responseIds, expectedModelHash, ...
        rawCenter, rawStatus, phaseCenterSeeds, seedFrequencyIndices, evidence);
    seedFrequencyIndices = seedFrequencyIndices(:);
    validateRawCentersAgainstResponses(responseSamples, rawCenter, ...
        rawStatus, options);
    intervalCount = frequencyCount-1;
    alignedCenter = NaN(size(rawCenter));
    branchShiftTurns = NaN(size(rawCenter));
    branchStatus = strings(size(rawStatus));
    reasonCodes = strings(size(rawStatus));
    intervalStatus = strings(responseCount, intervalCount);
    responseScale = NaN(responseCount, intervalCount);
    referenceAccretivityMarginNormalized = ...
        NaN(responseCount, intervalCount);
    verifiedMarginNormalized = NaN(responseCount, intervalCount);
    observedEndpointDeviationNormalized = ...
        NaN(responseCount, intervalCount);

    for responseIndex = 1:responseCount
        seedIndex = seedFrequencyIndices(responseIndex);
        if seedIndex > 1
            branchStatus(responseIndex, 1:seedIndex-1) = ...
                "phase-branch-indeterminate";
            reasonCodes(responseIndex, 1:seedIndex-1) = ...
                "phase-before-explicit-seed";
            intervalStatus(responseIndex, 1:seedIndex-1) = "indeterminate";
        end
        if rawStatus(responseIndex, seedIndex) ~= "resolved"
            branchStatus(responseIndex, seedIndex) = "phase-unavailable";
            reasonCodes(responseIndex, seedIndex) = "raw-phase-unavailable";
            continue;
        end
        seed = phaseCenterSeeds(responseIndex);
        if ~isfinite(seed)
            branchStatus(responseIndex, seedIndex) = ...
                "phase-branch-indeterminate";
            reasonCodes(responseIndex, seedIndex) = "phase-branch-unanchored";
            continue;
        end
        rawSeedCenter = rawCenter(responseIndex, seedIndex);
        shiftTurns = round((seed-rawSeedCenter)/(2*pi));
        alignedSeedCenter = rawSeedCenter+2*pi*shiftTurns;
        if abs(seed-alignedSeedCenter) > options.SeedConsistencyTolerance
            branchStatus(responseIndex, seedIndex) = ...
                "phase-branch-indeterminate";
            reasonCodes(responseIndex, seedIndex) = ...
                "explicit-seed-inconsistent-with-phase-center";
            continue;
        end
        alignedCenter(responseIndex, seedIndex) = alignedSeedCenter;
        branchShiftTurns(responseIndex, seedIndex) = shiftTurns;
        branchStatus(responseIndex, seedIndex) = "verified-from-explicit-seed";
        reasonCodes(responseIndex, seedIndex) = "phase-branch-anchored-by-seed";

        for intervalIndex = seedIndex:intervalCount
            rightIndex = intervalIndex+1;
            previousCenter = alignedCenter(responseIndex, intervalIndex);
            if ~isfinite(previousCenter) || ...
                    rawStatus(responseIndex, rightIndex) ~= "resolved"
                markIndeterminate("phase-gap-or-unavailable");
                continue;
            end

            Aleft = responseSamples{responseIndex}(:, :, intervalIndex);
            Aright = responseSamples{responseIndex}(:, :, rightIndex);
            theta = evidence.rotationThetaRad(responseIndex, intervalIndex);
            delta = evidence.responseDeviationUpperBound2Norm( ...
                responseIndex, intervalIndex);
            if ~isfinite(theta) || ~isfinite(delta)
                markIndeterminate("half-plane-evidence-unavailable");
                continue;
            end
            scale = max([max(abs(real(Aleft)), [], 'all'), ...
                max(abs(imag(Aleft)), [], 'all'), ...
                max(abs(real(Aright)), [], 'all'), ...
                max(abs(imag(Aright)), [], 'all'), delta, 1]);
            scaledLeft = Aleft/scale;
            scaledRight = Aright/scale;
            scaledDelta = delta/scale;
            rotated = exp(-1i*theta)*scaledLeft;
            rotatedHermitian = (rotated+rotated')/2;
            mu = min(real(eig(rotatedHermitian, 'vector')));
            endpointDeviation = norm(scaledRight-scaledLeft, 2);
            margin = mu-scaledDelta;
            responseScale(responseIndex, intervalIndex) = scale;
            referenceAccretivityMarginNormalized( ...
                responseIndex, intervalIndex) = mu;
            observedEndpointDeviationNormalized( ...
                responseIndex, intervalIndex) = endpointDeviation;
            verifiedMarginNormalized(responseIndex, intervalIndex) = margin;

            if any(~isfinite(rotatedHermitian), 'all') || ...
                    ~isfinite(mu) || ~isfinite(endpointDeviation) || ...
                    ~isfinite(margin)
                markIndeterminate("nonfinite-half-plane-computation");
            elseif endpointDeviation > scaledDelta+ ...
                    options.ConsistencyTolerance
                markIndeterminate("deviation-bound-inconsistent-with-endpoints", ...
                    "invalid-bound");
            elseif margin <= options.PositivityTolerance
                markIndeterminate("common-open-half-plane-not-verified");
            else
                thetaAligned = theta+2*pi*round( ...
                    (previousCenter-theta)/(2*pi));
                rawRight = rawCenter(responseIndex, rightIndex);
                candidate = rawRight+2*pi*round( ...
                    (thetaAligned-rawRight)/(2*pi));
                if abs(previousCenter-thetaAligned) >= pi/2 || ...
                        abs(candidate-thetaAligned) >= pi/2
                    markIndeterminate("phase-center-inconsistent-with-half-plane");
                else
                    alignedCenter(responseIndex, rightIndex) = candidate;
                    branchShiftTurns(responseIndex, rightIndex) = round( ...
                        (candidate-rawRight)/(2*pi));
                    branchStatus(responseIndex, rightIndex) = ...
                        "verified-under-common-half-plane-bound";
                    reasonCodes(responseIndex, rightIndex) = ...
                        "unique-phase-branch-from-common-half-plane";
                    intervalStatus(responseIndex, intervalIndex) = "verified";
                end
            end
        end
    end

    if all(intervalStatus(:) == "verified") && ...
            all(branchStatus(sub2ind(size(branchStatus), ...
                (1:responseCount).', seedFrequencyIndices)) == ...
                "verified-from-explicit-seed")
        verificationStatus = ...
            "branch-verified-under-supplied-deviation-bounds";
    else
        verificationStatus = "indeterminate";
    end
    result = struct( ...
        'center', alignedCenter, ...
        'branchShiftTurns', branchShiftTurns, ...
        'branchStatus', branchStatus, ...
        'reasonCodes', reasonCodes, ...
        'intervalStatus', intervalStatus, ...
        'responseScale', responseScale, ...
        'referenceAccretivityMarginNormalized', ...
            referenceAccretivityMarginNormalized, ...
        'verifiedMarginNormalized', verifiedMarginNormalized, ...
        'observedEndpointDeviationNormalized', ...
            observedEndpointDeviationNormalized, ...
        'evidence', evidence, ...
        'floatingPointCertified', false, ...
        'verificationStatus', verificationStatus, ...
        'scope', "phase-branch-and-strict-sectoriality-only", ...
        'method', "common-open-half-plane-deviation-bound-v1", ...
        'interpretationBoundary', ...
            ['This result verifies phase-branch continuity and strict ', ...
             'sectoriality on the stated finite intervals. It does not ', ...
             'verify the mixed gain-phase inequalities between samples, ', ...
             'the zero/infinite-frequency endpoints, or theorem preconditions.']);

    function markIndeterminate(reason, status)
        if nargin < 2
            status = "indeterminate";
        end
        branchStatus(responseIndex, rightIndex) = ...
            "phase-branch-indeterminate";
        reasonCodes(responseIndex, rightIndex) = reason;
        intervalStatus(responseIndex, intervalIndex) = status;
    end
end

function [responseCount, frequencyCount, evidence] = validateInputs( ...
        responseSamples, frequenciesHz, responseIds, expectedModelHash, ...
        rawCenter, rawStatus, phaseCenterSeeds, seedFrequencyIndices, evidence)
    if ~(iscell(responseSamples) && isvector(responseSamples) && ...
            ~isempty(responseSamples))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidResponses', ...
            'responseSamples must be a nonempty cell vector.');
    end
    responseCount = numel(responseSamples);
    if ~(isnumeric(frequenciesHz) && isreal(frequenciesHz) && ...
            isvector(frequenciesHz) && numel(frequenciesHz) >= 2 && ...
            all(isfinite(frequenciesHz)) && all(diff(frequenciesHz) > 0))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidGrid', ...
            'frequenciesHz must be a finite strictly increasing vector.');
    end
    frequenciesHz = frequenciesHz(:).';
    if ~(isstring(responseIds) && isvector(responseIds) && ...
            numel(responseIds) == responseCount && ...
            all(strlength(responseIds) > 0) && ...
            numel(unique(responseIds)) == responseCount)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidResponseIds', ...
            'responseIds must uniquely identify every response.');
    end
    responseIds = responseIds(:);
    expectedModelHash = string(expectedModelHash);
    if ~(isscalar(expectedModelHash) && strlength(expectedModelHash) > 0)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidModelHash', ...
            'expectedModelHash must be nonempty.');
    end
    if ~(isnumeric(rawCenter) && isreal(rawCenter) && ...
            ismatrix(rawCenter) && size(rawCenter, 1) == responseCount && ...
            size(rawCenter, 2) >= 2)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidCenter', ...
            'rawCenter must have one row per response and at least two columns.');
    end
    frequencyCount = size(rawCenter, 2);
    if numel(frequenciesHz) ~= frequencyCount
        error('gfm:verifyHalfPlanePhaseBranchIntervals:GridSizeMismatch', ...
            'Frequency-grid length must match the response sample count.');
    end
    for index = 1:responseCount
        response = responseSamples{index};
        if ~(isnumeric(response) && ndims(response) <= 3 && ...
                size(response, 1) == size(response, 2) && ...
                size(response, 3) == frequencyCount)
            error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidResponses', ...
                'Each response must be a square matrix sample array.');
        end
    end
    if ~(isstring(rawStatus) && isequal(size(rawStatus), size(rawCenter)))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidStatus', ...
            'rawStatus must be a same-size string array.');
    end
    if ~(isnumeric(phaseCenterSeeds) && isreal(phaseCenterSeeds) && ...
            isvector(phaseCenterSeeds) && ...
            numel(phaseCenterSeeds) == responseCount)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidSeeds', ...
            'One phase-center seed is required per response.');
    end
    if ~(isnumeric(seedFrequencyIndices) && isreal(seedFrequencyIndices) && ...
            isvector(seedFrequencyIndices) && ...
            numel(seedFrequencyIndices) == responseCount && ...
            all(isfinite(seedFrequencyIndices)) && ...
            all(seedFrequencyIndices == floor(seedFrequencyIndices)) && ...
            all(seedFrequencyIndices >= 1) && ...
            all(seedFrequencyIndices <= frequencyCount))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidSeedIndices', ...
            'One in-range integer seed index is required per response.');
    end
    required = {'responseDeviationUpperBound2Norm', 'rotationThetaRad', ...
        'frequencyGridHz', 'responseIds', 'frequencyUnit', 'boundMethod', ...
        'modelHash', 'referencePoint', 'assuranceLevel', ...
        'floatingPointCertified', 'roundoffBoundIncluded', ...
        'independentVariable', 'derivativeUnit'};
    if ~(isstruct(evidence) && isscalar(evidence) && ...
            all(isfield(evidence, required)))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidEvidence', ...
            'Evidence is missing required numeric or provenance fields.');
    end
    expectedSize = [responseCount, frequencyCount-1];
    numericFields = {'responseDeviationUpperBound2Norm', 'rotationThetaRad'};
    for index = 1:numel(numericFields)
        value = evidence.(numericFields{index});
        if ~(isnumeric(value) && isreal(value) && ...
                isequal(size(value), expectedSize))
            error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidEvidence', ...
                '%s has an invalid size or type.', numericFields{index});
        end
    end
    if any(evidence.responseDeviationUpperBound2Norm(:) < 0)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidEvidence', ...
            'Response-deviation bounds must be nonnegative.');
    end
    evidence.frequencyUnit = string(evidence.frequencyUnit);
    evidence.boundMethod = string(evidence.boundMethod);
    evidence.modelHash = string(evidence.modelHash);
    evidence.referencePoint = string(evidence.referencePoint);
    evidence.assuranceLevel = string(evidence.assuranceLevel);
    evidence.independentVariable = string(evidence.independentVariable);
    evidence.derivativeUnit = string(evidence.derivativeUnit);
    evidence.responseIds = string(evidence.responseIds(:));
    if ~(isnumeric(evidence.frequencyGridHz) && ...
            isequal(evidence.frequencyGridHz(:).', frequenciesHz))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:EvidenceGridMismatch', ...
            'Evidence frequencyGridHz does not match the evaluated grid.');
    end
    if ~isequal(evidence.responseIds, responseIds)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:EvidenceResponseMismatch', ...
            'Evidence responseIds do not match the evaluated response order.');
    end
    if evidence.modelHash ~= expectedModelHash
        error('gfm:verifyHalfPlanePhaseBranchIntervals:EvidenceModelMismatch', ...
            'Evidence modelHash does not match the evaluated model.');
    end
    if ~(isscalar(evidence.frequencyUnit) && evidence.frequencyUnit == "Hz" && ...
            isscalar(evidence.boundMethod) && strlength(evidence.boundMethod) > 0 && ...
            isscalar(evidence.referencePoint) && ...
                evidence.referencePoint == "left-endpoint" && ...
            isscalar(evidence.assuranceLevel) && ...
                evidence.assuranceLevel == ...
                "double-precision-numerical-bound" && ...
            islogical(evidence.floatingPointCertified) && ...
                isscalar(evidence.floatingPointCertified) && ...
                ~evidence.floatingPointCertified && ...
            islogical(evidence.roundoffBoundIncluded) && ...
                isscalar(evidence.roundoffBoundIncluded) && ...
                ~evidence.roundoffBoundIncluded && ...
            isscalar(evidence.independentVariable) && ...
                evidence.independentVariable == "frequency" && ...
            isscalar(evidence.derivativeUnit) && ...
                evidence.derivativeUnit == "per-Hz")
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidEvidence', ...
            ['Evidence must declare left-endpoint, per-Hz, double-precision ', ...
             'numerical bounds without floating-point certification.']);
    end
end

function options = validateOptions(options)
    defaults = struct('PositivityTolerance', 1e-10, ...
        'ConsistencyTolerance', 1e-10, ...
        'SeedConsistencyTolerance', 1e-8, ...
        'PhaseCenterConsistencyTolerance', 1e-8, ...
        'PhaseOptions', struct());
    if ~(isstruct(options) && isscalar(options))
        error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidOptions', ...
            'options must be a scalar struct.');
    end
    unknown = setdiff(fieldnames(options), fieldnames(defaults));
    if ~isempty(unknown)
        error('gfm:verifyHalfPlanePhaseBranchIntervals:UnknownOption', ...
            'Unknown option: %s.', unknown{1});
    end
    names = fieldnames(defaults);
    for index = 1:numel(names)
        if ~isfield(options, names{index})
            options.(names{index}) = defaults.(names{index});
        end
        value = options.(names{index});
        if strcmp(names{index}, 'PhaseOptions')
            if ~(isstruct(value) && isscalar(value))
                error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidOption', ...
                    'PhaseOptions must be a scalar struct.');
            end
        elseif ~(isnumeric(value) && isreal(value) && isscalar(value) && ...
                isfinite(value) && value >= 0)
            error('gfm:verifyHalfPlanePhaseBranchIntervals:InvalidOption', ...
                '%s must be a finite nonnegative scalar.', names{index});
        end
    end
end

function validateRawCentersAgainstResponses(responseSamples, rawCenter, ...
        rawStatus, options)
    for responseIndex = 1:numel(responseSamples)
        for frequencyIndex = 1:size(rawCenter, 2)
            if rawStatus(responseIndex, frequencyIndex) ~= "resolved"
                continue;
            end
            phase = computeStrictSectorialPhaseInterval( ...
                responseSamples{responseIndex}(:, :, frequencyIndex), ...
                options.PhaseOptions);
            if phase.status ~= "resolved"
                error('gfm:verifyHalfPlanePhaseBranchIntervals:RawCenterMismatch', ...
                    'A resolved raw center is inconsistent with the response.');
            end
            computedCenter = (phase.lowerPhase+phase.upperPhase)/2;
            circularDifference = abs(angle(exp(1i*( ...
                rawCenter(responseIndex, frequencyIndex)-computedCenter))));
            if circularDifference > options.PhaseCenterConsistencyTolerance
                error('gfm:verifyHalfPlanePhaseBranchIntervals:RawCenterMismatch', ...
                    'A raw phase center does not match the response matrix.');
            end
        end
    end
end
